p8105\_hw2\_lk2761
================
Lorraine Kwok
09/27/2019

## Problem 1

This problem uses the 2019 Mr. Trash Wheel dataset focusing on the data
for Mr. Trash wheel and precipitation in 2017 and 2018.

``` r
# import and clean Mr. Trash Wheel sheet 

trash_wheel_data = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = 1, 
             range = cell_cols("A:N")) %>%
  janitor::clean_names(dat = .) %>%
  drop_na(data = ., dumpster) %>%
  mutate(.data = ., 
         sports_balls = round(sports_balls, digits = 0),
         sports_balls_int = as.integer(sports_balls),
         homes_powered_rd = round(homes_powered, digits = 2)) %>%
  select(.data = ., -sports_balls, -homes_powered)

trash_wheel_data
```

    ## # A tibble: 344 x 14
    ##    dumpster month  year date                weight_tons volume_cubic_ya…
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>            <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31               18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74               13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45               15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06               18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71               13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52               14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76               18
    ## # … with 334 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls_int <int>,
    ## #   homes_powered_rd <dbl>

``` r
# I could not figure out how to write inline R code that would filter the data by year and produce a mean so I am calculating it in this code chunk and calling for it below. 

trash_wheel_data %>%
  filter(.data = ., year == "2017") %>%
  mutate(.data = ., as.numeric(sports_balls_int)) %>%
  summarize(sports_ball_med = median(sports_balls_int, na.rm = TRUE))
```

    ## # A tibble: 1 x 1
    ##   sports_ball_med
    ##             <int>
    ## 1               8

``` r
# import and clean 2017 precipitation data 

precip_2017 = 
  read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = 6) %>%
  janitor::clean_names(dat = .) %>%
  rename(.data = ., month = precipitation_in, total_inches = x2) %>%
  filter(.data = ., month != "Month") %>%
  drop_na(data = .)  %>%
  mutate(.data = ., year = 2017) 
```

    ## New names:
    ## * `` -> ...2

``` r
precip_2017
```

    ## # A tibble: 12 x 3
    ##    month total_inches        year
    ##    <chr> <chr>              <dbl>
    ##  1 1     2.34                2017
    ##  2 2     1.46                2017
    ##  3 3     3.57                2017
    ##  4 4     3.99                2017
    ##  5 5     5.64                2017
    ##  6 6     1.4                 2017
    ##  7 7     7.09                2017
    ##  8 8     4.4400000000000004  2017
    ##  9 9     1.95                2017
    ## 10 10    0                   2017
    ## 11 11    0.11                2017
    ## 12 12    0.94                2017

``` r
# import and clean 2018 precipitation data

precip_2018 = 
   read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = 5) %>%
  janitor::clean_names(dat = .) %>%
  rename(.data = ., month = precipitation_in, total_inches = x2) %>%
  filter(.data = ., month != "Month") %>%
  drop_na(data = .) %>%
  mutate(.data = ., year = 2018) 
```

    ## New names:
    ## * `` -> ...2

``` r
precip_2018
```

    ## # A tibble: 12 x 3
    ##    month total_inches        year
    ##    <chr> <chr>              <dbl>
    ##  1 1     0.94                2018
    ##  2 2     4.8                 2018
    ##  3 3     2.69                2018
    ##  4 4     4.6900000000000004  2018
    ##  5 5     9.27                2018
    ##  6 6     4.7699999999999996  2018
    ##  7 7     10.199999999999999  2018
    ##  8 8     6.45                2018
    ##  9 9     10.47               2018
    ## 10 10    2.12                2018
    ## 11 11    7.82                2018
    ## 12 12    6.11                2018

``` r
# create new dataset by combining precip_2017 and precip_2018

precip_combined = 
  bind_rows(precip_2017, precip_2018) %>%
  mutate(.data = ., 
         total_in = round(as.numeric(total_inches), digits = 2),
         month = month.name[as.numeric(month)]) %>% 
  select(.data = ., year, month, total_in, -total_inches)

precip_combined
```

    ## # A tibble: 24 x 3
    ##     year month     total_in
    ##    <dbl> <chr>        <dbl>
    ##  1  2017 January       2.34
    ##  2  2017 February      1.46
    ##  3  2017 March         3.57
    ##  4  2017 April         3.99
    ##  5  2017 May           5.64
    ##  6  2017 June          1.4 
    ##  7  2017 July          7.09
    ##  8  2017 August        4.44
    ##  9  2017 September     1.95
    ## 10  2017 October       0   
    ## # … with 14 more rows

This code chunk calculates the total inches of precipitation in 2018.

``` r
precip_combined %>%
  filter(.data = ., year == "2018") %>%
  summarize(total_rain_2018 = sum(total_in, na.rm = TRUE))
```

    ## # A tibble: 1 x 1
    ##   total_rain_2018
    ##             <dbl>
    ## 1            70.3

The Mr. Trash Wheel dataset consists of 344 observations. The mean
weight of trash removed by Mr. Trash Wheel in the Inner Harbor of
Baltimore, Maryland, as denoted by the variable *weight\_tons* between
May 2014 and June 2019 is 3.26 tons and the mean volume, denoted by
*volume\_cubic\_yards* is 15.54 cubic yards. The median number of sports
balls removed in 2017 was 8 balls.

Data on precipitation in 2017 and 2018 were combined into one dataset,
which is made up of 24 observations. The average amount of rainfall from
January 2017 to December 2018 was 4.3 inches. The total precipitation in
2018 was 70.3 inches.

## Problem 2

We are now using the FiveThirtyEight data.

``` r
# create dataframe with data on politicians
# In this dataset, for prez_gop, there were values of "2," which still resulted in coding of "0" in the prez_dem variable. 

pols_month_df =
  read.csv("./data/fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names(dat = .) %>%
  separate(., mon, into = c("year", "month", "day")) %>%
  mutate(.data = .,
         prez_dem = recode(prez_dem, `1` = "dem", `0` = "gop"), 
         president = prez_dem,
         month = month.name[as.numeric(month)]) %>%
  select(.data = ., -prez_dem, -prez_gop, -day)

pols_month_df
```

    ##     year     month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ## 1   1947   January      23      51     253      23      45     198
    ## 2   1947  February      23      51     253      23      45     198
    ## 3   1947     March      23      51     253      23      45     198
    ## 4   1947     April      23      51     253      23      45     198
    ## 5   1947       May      23      51     253      23      45     198
    ## 6   1947      June      23      51     253      23      45     198
    ## 7   1947      July      23      51     253      23      45     198
    ## 8   1947    August      23      51     253      23      45     198
    ## 9   1947 September      23      51     253      23      45     198
    ## 10  1947   October      23      51     253      23      45     198
    ## 11  1947  November      24      51     253      23      45     198
    ## 12  1947  December      24      51     253      23      45     198
    ## 13  1948   January      22      53     253      24      48     198
    ## 14  1948  February      22      53     253      24      48     198
    ## 15  1948     March      22      53     253      24      48     198
    ## 16  1948     April      22      53     253      24      48     198
    ## 17  1948       May      22      53     253      24      48     198
    ## 18  1948      June      22      53     253      24      48     198
    ## 19  1948      July      22      53     253      24      48     198
    ## 20  1948    August      22      53     253      24      48     198
    ## 21  1948 September      22      53     253      24      48     198
    ## 22  1948   October      22      53     253      24      48     198
    ## 23  1948  November      22      53     253      24      48     198
    ## 24  1948  December      22      53     253      24      48     198
    ## 25  1949   January      18      45     177      29      58     269
    ## 26  1949  February      18      45     177      29      58     269
    ## 27  1949     March      18      45     177      29      58     269
    ## 28  1949     April      18      45     177      29      58     269
    ## 29  1949       May      18      45     177      29      58     269
    ## 30  1949      June      18      45     177      29      58     269
    ## 31  1949      July      18      45     177      30      58     269
    ## 32  1949    August      18      45     177      30      58     269
    ## 33  1949 September      18      45     177      30      58     269
    ## 34  1949   October      18      45     177      30      58     269
    ## 35  1949  November      18      45     177      30      58     269
    ## 36  1949  December      18      45     177      30      58     269
    ## 37  1950   January      18      44     177      29      57     269
    ## 38  1950  February      18      44     177      29      57     269
    ## 39  1950     March      18      44     177      29      57     269
    ## 40  1950     April      18      44     177      29      57     269
    ## 41  1950       May      18      44     177      29      57     269
    ## 42  1950      June      18      44     177      29      57     269
    ## 43  1950      July      18      44     177      29      57     269
    ## 44  1950    August      18      44     177      29      57     269
    ## 45  1950 September      18      44     177      29      57     269
    ## 46  1950   October      18      44     177      29      57     269
    ## 47  1950  November      18      44     177      29      57     269
    ## 48  1950  December      18      44     177      29      57     269
    ## 49  1951   January      24      47     207      22      51     242
    ## 50  1951  February      24      47     207      22      51     242
    ## 51  1951     March      24      47     207      22      51     242
    ## 52  1951     April      24      47     207      22      51     242
    ## 53  1951       May      24      47     207      22      51     242
    ## 54  1951      June      24      47     207      22      51     242
    ## 55  1951      July      24      47     207      22      51     242
    ## 56  1951    August      24      47     207      22      51     242
    ## 57  1951 September      24      47     207      22      51     242
    ## 58  1951   October      25      47     207      22      51     242
    ## 59  1951  November      25      47     207      22      51     242
    ## 60  1951  December      25      47     207      22      51     242
    ## 61  1952   January      24      50     207      22      50     242
    ## 62  1952  February      24      50     207      22      50     242
    ## 63  1952     March      24      50     207      22      50     242
    ## 64  1952     April      24      50     207      22      50     242
    ## 65  1952       May      24      50     207      22      50     242
    ## 66  1952      June      24      50     207      22      50     242
    ## 67  1952      July      24      50     207      22      50     242
    ## 68  1952    August      24      50     207      22      50     242
    ## 69  1952 September      24      50     207      22      50     242
    ## 70  1952   October      24      50     207      22      50     242
    ## 71  1952  November      24      50     207      22      50     242
    ## 72  1952  December      24      50     207      22      50     242
    ## 73  1953   January      29      50     222      17      49     220
    ## 74  1953  February      29      50     222      17      49     220
    ## 75  1953     March      29      50     222      17      49     220
    ## 76  1953     April      29      50     222      17      49     220
    ## 77  1953       May      29      50     222      17      49     220
    ## 78  1953      June      29      50     222      17      49     220
    ## 79  1953      July      29      50     222      17      49     220
    ## 80  1953    August      29      50     222      17      49     220
    ## 81  1953 September      29      50     222      17      49     220
    ## 82  1953   October      30      50     222      18      49     220
    ## 83  1953  November      30      50     222      18      49     220
    ## 84  1953  December      30      50     222      18      49     220
    ## 85  1954   January      29      55     222      18      53     220
    ## 86  1954  February      29      55     222      18      53     220
    ## 87  1954     March      29      55     222      18      53     220
    ## 88  1954     April      29      55     222      18      53     220
    ## 89  1954       May      29      55     222      18      53     220
    ## 90  1954      June      29      55     222      18      53     220
    ## 91  1954      July      29      55     222      18      53     220
    ## 92  1954    August      29      55     222      18      53     220
    ## 93  1954 September      29      55     222      18      53     220
    ## 94  1954   October      29      55     222      18      53     220
    ## 95  1954  November      29      55     222      19      53     220
    ## 96  1954  December      29      55     222      19      53     220
    ## 97  1955   January      21      47     204      26      48     237
    ## 98  1955  February      21      47     204      26      48     237
    ## 99  1955     March      21      47     204      26      48     237
    ## 100 1955     April      21      47     204      26      48     237
    ## 101 1955       May      21      47     204      26      48     237
    ## 102 1955      June      21      47     204      26      48     237
    ## 103 1955      July      21      47     204      26      48     237
    ## 104 1955    August      21      47     204      26      48     237
    ## 105 1955 September      21      47     204      26      48     237
    ## 106 1955   October      21      47     204      26      48     237
    ## 107 1955  November      21      47     204      26      48     237
    ## 108 1955  December      21      47     204      26      48     237
    ## 109 1956   January      21      49     204      26      51     237
    ## 110 1956  February      21      49     204      26      51     237
    ## 111 1956     March      21      49     204      26      51     237
    ## 112 1956     April      21      49     204      26      50     237
    ## 113 1956       May      21      49     204      26      50     237
    ## 114 1956      June      21      49     204      26      50     237
    ## 115 1956      July      21      49     204      26      50     237
    ## 116 1956    August      21      49     204      26      50     237
    ## 117 1956 September      21      49     204      26      50     237
    ## 118 1956   October      21      49     204      26      50     237
    ## 119 1956  November      21      49     204      26      51     237
    ## 120 1956  December      21      49     204      26      51     237
    ## 121 1957   January      19      47     203      28      52     242
    ## 122 1957  February      19      47     203      28      52     242
    ## 123 1957     March      19      47     203      28      52     242
    ## 124 1957     April      19      47     203      28      52     242
    ## 125 1957       May      19      47     203      28      52     242
    ## 126 1957      June      19      47     203      28      52     242
    ## 127 1957      July      19      47     203      28      52     242
    ## 128 1957    August      19      47     203      28      52     242
    ## 129 1957 September      20      47     203      28      52     242
    ## 130 1957   October      20      47     203      28      52     242
    ## 131 1957  November      20      47     203      28      52     242
    ## 132 1957  December      20      47     203      28      52     242
    ## 133 1958   January      20      47     203      28      52     242
    ## 134 1958  February      20      47     203      28      52     242
    ## 135 1958     March      20      47     203      28      52     242
    ## 136 1958     April      20      47     203      28      52     242
    ## 137 1958       May      20      47     203      28      52     242
    ## 138 1958      June      20      47     203      28      52     242
    ## 139 1958      July      20      47     203      28      52     242
    ## 140 1958    August      20      47     203      28      52     242
    ## 141 1958 September      20      47     203      28      52     242
    ## 142 1958   October      20      47     203      28      52     242
    ## 143 1958  November      20      47     203      28      52     242
    ## 144 1958  December      20      47     203      28      52     242
    ## 145 1959   January      15      35     159      35      65     289
    ## 146 1959  February      15      35     159      35      65     289
    ## 147 1959     March      15      35     159      35      65     289
    ## 148 1959     April      15      35     159      35      65     289
    ## 149 1959       May      15      35     159      35      65     289
    ## 150 1959      June      15      35     159      35      65     289
    ## 151 1959      July      15      35     159      35      65     289
    ## 152 1959    August      15      35     159      35      65     289
    ## 153 1959 September      15      35     159      35      65     289
    ## 154 1959   October      15      35     159      35      65     289
    ## 155 1959  November      15      35     159      35      65     289
    ## 156 1959  December      15      35     159      35      65     289
    ## 157 1960   January      16      35     159      34      70     289
    ## 158 1960  February      16      35     159      34      70     289
    ## 159 1960     March      16      35     159      34      70     289
    ## 160 1960     April      16      35     159      34      70     289
    ## 161 1960       May      16      35     159      34      70     289
    ## 162 1960      June      16      35     159      34      70     289
    ## 163 1960      July      16      35     159      34      70     289
    ## 164 1960    August      16      35     159      34      70     289
    ## 165 1960 September      17      35     159      34      70     289
    ## 166 1960   October      17      35     159      34      70     289
    ## 167 1960  November      17      35     159      34      70     289
    ## 168 1960  December      17      35     159      34      70     289
    ## 169 1961   January      16      37     176      34      64     273
    ## 170 1961  February      16      37     176      34      64     273
    ## 171 1961     March      16      37     176      34      64     273
    ## 172 1961     April      16      37     176      34      64     273
    ## 173 1961       May      16      37     176      34      64     273
    ## 174 1961      June      16      37     176      34      64     273
    ## 175 1961      July      16      37     176      34      64     273
    ## 176 1961    August      16      37     176      34      64     273
    ## 177 1961 September      16      37     176      34      64     273
    ## 178 1961   October      16      37     176      34      64     273
    ## 179 1961  November      16      37     176      34      64     273
    ## 180 1961  December      16      37     176      34      64     273
    ## 181 1962   January      16      42     176      34      65     273
    ## 182 1962  February      16      42     176      34      65     273
    ## 183 1962     March      16      42     176      34      65     273
    ## 184 1962     April      16      42     176      34      65     273
    ## 185 1962       May      16      42     176      34      65     273
    ## 186 1962      June      16      42     176      34      65     273
    ## 187 1962      July      16      42     176      34      65     273
    ## 188 1962    August      16      42     176      34      65     273
    ## 189 1962 September      16      42     176      34      65     273
    ## 190 1962   October      16      42     176      34      65     273
    ## 191 1962  November      16      42     176      34      65     273
    ## 192 1962  December      16      42     176      34      65     273
    ## 193 1963   January      17      34     182      33      68     262
    ## 194 1963  February      17      34     182      33      68     262
    ## 195 1963     March      16      34     182      34      68     262
    ## 196 1963     April      16      34     182      34      68     262
    ## 197 1963       May      16      34     182      34      68     262
    ## 198 1963      June      16      34     182      34      68     262
    ## 199 1963      July      16      34     182      34      68     262
    ## 200 1963    August      16      34     182      34      68     262
    ## 201 1963 September      16      34     182      34      68     262
    ## 202 1963   October      16      34     182      34      68     262
    ## 203 1963  November      16      34     182      34      68     262
    ## 204 1963  December      16      34     182      34      68     262
    ## 205 1964   January      16      34     182      34      71     262
    ## 206 1964  February      16      34     182      34      71     262
    ## 207 1964     March      16      34     182      34      71     262
    ## 208 1964     April      16      34     182      34      71     262
    ## 209 1964       May      16      34     182      34      71     262
    ## 210 1964      June      16      34     182      34      71     262
    ## 211 1964      July      16      34     182      34      71     262
    ## 212 1964    August      16      34     182      34      71     262
    ## 213 1964 September      16      34     182      34      71     262
    ## 214 1964   October      16      34     182      34      71     262
    ## 215 1964  November      16      34     182      34      71     262
    ## 216 1964  December      16      34     182      34      71     262
    ## 217 1965   January      17      32     141      33      69     301
    ## 218 1965  February      17      32     141      33      69     301
    ## 219 1965     March      17      32     141      33      69     301
    ## 220 1965     April      17      32     141      33      69     301
    ## 221 1965       May      17      32     141      33      69     301
    ## 222 1965      June      17      32     141      33      69     301
    ## 223 1965      July      17      32     141      33      69     301
    ## 224 1965    August      17      32     141      33      69     301
    ## 225 1965 September      17      32     141      33      69     301
    ## 226 1965   October      17      32     141      33      69     301
    ## 227 1965  November      17      32     141      33      69     301
    ## 228 1965  December      17      32     141      33      69     301
    ## 229 1966   January      18      33     141      33      70     301
    ## 230 1966  February      18      33     141      33      70     301
    ## 231 1966     March      18      33     141      33      70     301
    ## 232 1966     April      18      33     141      33      70     301
    ## 233 1966       May      18      33     141      33      70     301
    ## 234 1966      June      18      33     141      33      70     301
    ## 235 1966      July      18      33     141      33      70     301
    ## 236 1966    August      18      33     141      33      70     301
    ## 237 1966 September      18      33     141      33      70     301
    ## 238 1966   October      18      33     141      33      70     301
    ## 239 1966  November      18      33     141      33      70     301
    ## 240 1966  December      18      33     141      33      70     301
    ## 241 1967   January      25      36     188      27      64     251
    ## 242 1967  February      25      36     188      27      64     251
    ## 243 1967     March      25      36     188      27      64     251
    ## 244 1967     April      25      36     188      27      64     251
    ## 245 1967       May      25      36     188      27      64     251
    ## 246 1967      June      25      36     188      27      64     251
    ## 247 1967      July      25      36     188      27      64     251
    ## 248 1967    August      25      36     188      27      64     251
    ## 249 1967 September      25      36     188      27      64     251
    ## 250 1967   October      25      36     188      27      64     251
    ## 251 1967  November      25      36     188      27      64     251
    ## 252 1967  December      25      36     188      27      64     251
    ## 253 1968   January      26      39     188      26      65     251
    ## 254 1968  February      26      39     188      26      65     251
    ## 255 1968     March      26      39     188      26      65     251
    ## 256 1968     April      26      39     188      26      65     251
    ## 257 1968       May      26      39     188      26      65     251
    ## 258 1968      June      26      39     188      26      65     251
    ## 259 1968      July      26      39     188      26      65     251
    ## 260 1968    August      26      39     188      26      65     251
    ## 261 1968 September      26      39     188      26      65     251
    ## 262 1968   October      26      39     188      26      65     251
    ## 263 1968  November      26      39     188      26      65     251
    ## 264 1968  December      26      39     188      26      65     251
    ## 265 1969   January      31      43     199      22      57     250
    ## 266 1969  February      31      43     199      22      57     250
    ## 267 1969     March      31      43     199      22      57     250
    ## 268 1969     April      31      43     199      22      57     250
    ## 269 1969       May      31      43     199      22      57     250
    ## 270 1969      June      31      43     199      22      57     250
    ## 271 1969      July      31      43     199      22      57     250
    ## 272 1969    August      31      43     199      22      57     250
    ## 273 1969 September      31      43     199      22      57     250
    ## 274 1969   October      31      43     199      22      57     250
    ## 275 1969  November      31      43     199      22      57     250
    ## 276 1969  December      31      43     199      22      57     250
    ## 277 1970   January      32      43     199      20      58     250
    ## 278 1970  February      32      43     199      20      58     250
    ## 279 1970     March      32      43     199      20      58     250
    ## 280 1970     April      32      43     199      20      58     250
    ## 281 1970       May      32      43     199      20      58     250
    ## 282 1970      June      32      43     199      20      58     250
    ## 283 1970      July      32      43     199      20      58     250
    ## 284 1970    August      32      43     199      20      58     250
    ## 285 1970 September      32      43     199      20      58     250
    ## 286 1970   October      32      43     199      20      58     250
    ## 287 1970  November      32      43     199      20      58     250
    ## 288 1970  December      32      43     199      20      58     250
    ## 289 1971   January      21      44     185      30      55     259
    ## 290 1971  February      21      44     185      30      55     259
    ## 291 1971     March      21      44     185      30      55     259
    ## 292 1971     April      21      44     185      30      55     259
    ## 293 1971       May      21      44     185      30      55     259
    ## 294 1971      June      21      44     185      30      55     259
    ## 295 1971      July      21      44     185      30      55     259
    ## 296 1971    August      21      44     185      30      55     259
    ## 297 1971 September      21      44     185      30      55     259
    ## 298 1971   October      21      44     185      30      55     259
    ## 299 1971  November      21      44     185      30      55     259
    ## 300 1971  December      21      44     185      30      55     259
    ## 301 1972   January      20      44     185      31      57     259
    ## 302 1972  February      20      44     185      31      57     259
    ## 303 1972     March      20      44     185      31      57     259
    ## 304 1972     April      20      44     185      31      57     259
    ## 305 1972       May      20      44     185      31      57     259
    ## 306 1972      June      20      44     185      31      57     259
    ## 307 1972      July      20      44     185      31      57     259
    ## 308 1972    August      20      44     185      31      57     259
    ## 309 1972 September      20      44     185      31      57     259
    ## 310 1972   October      20      44     185      31      57     259
    ## 311 1972  November      20      44     185      31      57     259
    ## 312 1972  December      20      44     185      31      57     259
    ## 313 1973   January      19      42     195      32      56     249
    ## 314 1973  February      19      42     195      32      56     249
    ## 315 1973     March      19      42     195      32      56     249
    ## 316 1973     April      19      42     195      32      56     249
    ## 317 1973       May      19      42     195      32      56     249
    ## 318 1973      June      19      42     195      32      56     249
    ## 319 1973      July      19      42     195      32      56     249
    ## 320 1973    August      20      42     195      32      56     249
    ## 321 1973 September      20      42     195      32      56     249
    ## 322 1973   October      20      42     195      32      56     249
    ## 323 1973  November      20      42     195      32      56     249
    ## 324 1973  December      20      42     195      32      56     249
    ## 325 1974   January      18      45     195      34      59     249
    ## 326 1974  February      18      45     195      34      59     249
    ## 327 1974     March      18      45     195      34      59     249
    ## 328 1974     April      18      45     195      34      59     249
    ## 329 1974       May      18      45     195      34      59     249
    ## 330 1974      June      18      45     195      34      59     249
    ## 331 1974      July      18      45     195      34      59     249
    ## 332 1974    August      18      45     195      34      59     249
    ## 333 1974 September      18      45     195      34      59     249
    ## 334 1974   October      18      45     195      34      59     249
    ## 335 1974  November      18      45     195      34      59     249
    ## 336 1974  December      18      45     195      34      59     249
    ## 337 1975   January      13      38     148      37      61     295
    ## 338 1975  February      13      38     148      37      61     295
    ## 339 1975     March      13      38     148      37      61     295
    ## 340 1975     April      13      38     148      37      61     295
    ## 341 1975       May      13      38     148      37      61     295
    ## 342 1975      June      13      38     148      37      61     295
    ## 343 1975      July      13      38     148      37      61     295
    ## 344 1975    August      13      38     148      37      61     295
    ## 345 1975 September      13      38     148      37      61     295
    ## 346 1975   October      13      38     148      37      61     295
    ## 347 1975  November      13      38     148      37      61     295
    ## 348 1975  December      13      38     148      37      61     295
    ## 349 1976   January      13      39     148      37      65     295
    ## 350 1976  February      13      39     148      37      65     295
    ## 351 1976     March      13      39     148      37      65     295
    ## 352 1976     April      13      39     148      37      65     295
    ## 353 1976       May      13      39     148      37      65     295
    ## 354 1976      June      13      39     148      37      65     295
    ## 355 1976      July      13      39     148      37      65     295
    ## 356 1976    August      13      39     148      37      65     295
    ## 357 1976 September      13      39     148      37      65     295
    ## 358 1976   October      13      39     148      37      65     295
    ## 359 1976  November      13      39     148      37      65     295
    ## 360 1976  December      13      39     148      37      65     295
    ## 361 1977   January      12      38     147      38      62     294
    ## 362 1977  February      12      38     147      38      62     294
    ## 363 1977     March      12      38     147      38      62     294
    ## 364 1977     April      12      38     147      38      62     294
    ## 365 1977       May      12      38     147      38      62     294
    ## 366 1977      June      12      38     147      39      62     294
    ## 367 1977      July      12      38     147      40      62     294
    ## 368 1977    August      12      38     147      40      62     294
    ## 369 1977 September      12      38     147      40      62     294
    ## 370 1977   October      12      38     147      40      62     294
    ## 371 1977  November      12      38     147      41      62     294
    ## 372 1977  December      12      38     147      41      62     294
    ## 373 1978   January      12      41     147      38      66     294
    ## 374 1978  February      12      41     147      38      66     294
    ## 375 1978     March      12      41     147      38      66     294
    ## 376 1978     April      12      41     147      38      66     294
    ## 377 1978       May      12      41     147      38      66     294
    ## 378 1978      June      12      41     147      38      66     294
    ## 379 1978      July      12      41     147      38      66     294
    ## 380 1978    August      12      41     147      39      66     294
    ## 381 1978 September      12      41     147      39      66     294
    ## 382 1978   October      12      41     147      39      66     294
    ## 383 1978  November      12      41     147      39      66     294
    ## 384 1978  December      12      41     147      39      66     294
    ## 385 1979   January      19      41     160      32      58     280
    ## 386 1979  February      19      41     160      32      58     280
    ## 387 1979     March      19      41     160      32      58     280
    ## 388 1979     April      19      41     160      32      58     280
    ## 389 1979       May      19      41     160      32      58     280
    ## 390 1979      June      19      41     160      32      58     280
    ## 391 1979      July      19      41     160      32      58     280
    ## 392 1979    August      19      41     160      32      58     280
    ## 393 1979 September      19      41     160      32      58     280
    ## 394 1979   October      19      41     160      32      58     280
    ## 395 1979  November      19      41     160      32      58     280
    ## 396 1979  December      19      41     160      32      58     280
    ## 397 1980   January      19      42     160      32      59     280
    ## 398 1980  February      19      42     160      32      59     280
    ## 399 1980     March      20      42     160      31      59     280
    ## 400 1980     April      20      42     160      31      59     280
    ## 401 1980       May      20      42     160      31      59     280
    ## 402 1980      June      20      42     160      31      59     280
    ## 403 1980      July      20      42     160      31      59     280
    ## 404 1980    August      20      42     160      31      59     280
    ## 405 1980 September      20      42     160      31      59     280
    ## 406 1980   October      20      42     160      31      59     280
    ## 407 1980  November      20      42     160      31      59     280
    ## 408 1980  December      20      42     160      31      59     280
    ## 409 1981   January      24      53     196      27      46     246
    ## 410 1981  February      24      53     196      27      46     246
    ## 411 1981     March      24      53     196      27      46     246
    ## 412 1981     April      24      53     196      27      46     246
    ## 413 1981       May      24      53     196      27      46     246
    ## 414 1981      June      24      53     196      27      46     246
    ## 415 1981      July      24      53     196      27      46     246
    ## 416 1981    August      24      53     196      27      46     246
    ## 417 1981 September      24      53     196      27      46     246
    ## 418 1981   October      24      53     196      27      46     246
    ## 419 1981  November      24      53     196      27      46     246
    ## 420 1981  December      24      53     196      27      46     246
    ## 421 1982   January      24      54     196      27      47     246
    ## 422 1982  February      24      54     196      27      47     246
    ## 423 1982     March      24      54     196      27      47     246
    ## 424 1982     April      24      54     196      27      47     246
    ## 425 1982       May      24      54     196      27      47     246
    ## 426 1982      June      24      54     196      27      47     246
    ## 427 1982      July      24      54     196      27      47     246
    ## 428 1982    August      24      54     196      27      47     246
    ## 429 1982 September      24      54     196      27      47     246
    ## 430 1982   October      24      54     196      27      47     246
    ## 431 1982  November      24      54     196      27      47     246
    ## 432 1982  December      24      54     196      27      47     246
    ## 433 1983   January      16      55     168      34      46     272
    ## 434 1983  February      16      55     168      34      46     272
    ## 435 1983     March      16      55     168      34      46     272
    ## 436 1983     April      16      55     168      34      46     271
    ## 437 1983       May      16      55     168      34      46     271
    ## 438 1983      June      16      55     168      34      46     271
    ## 439 1983      July      16      55     168      34      46     272
    ## 440 1983    August      16      55     168      34      46     272
    ## 441 1983 September      16      55     168      34      46     272
    ## 442 1983   October      16      55     168      34      46     272
    ## 443 1983  November      16      55     168      34      46     272
    ## 444 1983  December      16      55     168      34      46     272
    ## 445 1984   January      16      55     168      34      45     271
    ## 446 1984  February      16      55     168      34      45     271
    ## 447 1984     March      15      55     168      34      45     271
    ## 448 1984     April      15      55     168      34      45     271
    ## 449 1984       May      15      55     168      35      45     271
    ## 450 1984      June      15      55     168      35      45     271
    ## 451 1984      July      15      55     168      35      45     271
    ## 452 1984    August      15      55     168      35      45     271
    ## 453 1984 September      15      55     168      35      45     271
    ## 454 1984   October      15      55     168      35      45     271
    ## 455 1984  November      15      55     168      35      45     271
    ## 456 1984  December      15      55     168      35      45     271
    ## 457 1985   January      16      53     183      34      47     257
    ## 458 1985  February      16      53     183      34      47     257
    ## 459 1985     March      16      53     183      34      47     257
    ## 460 1985     April      16      53     183      34      47     257
    ## 461 1985       May      16      53     183      34      47     257
    ## 462 1985      June      16      53     183      34      47     257
    ## 463 1985      July      16      53     183      34      47     257
    ## 464 1985    August      16      53     183      34      47     257
    ## 465 1985 September      16      53     183      34      47     257
    ## 466 1985   October      16      53     183      34      47     257
    ## 467 1985  November      16      53     183      34      47     257
    ## 468 1985  December      16      53     183      34      47     257
    ## 469 1986   January      16      53     183      34      48     257
    ## 470 1986  February      16      53     183      34      48     257
    ## 471 1986     March      16      53     183      34      48     257
    ## 472 1986     April      16      53     183      34      48     257
    ## 473 1986       May      16      53     183      34      48     257
    ## 474 1986      June      16      53     183      34      48     257
    ## 475 1986      July      16      54     183      34      48     257
    ## 476 1986    August      16      54     183      34      48     257
    ## 477 1986 September      16      54     183      34      48     257
    ## 478 1986   October      16      54     183      34      48     257
    ## 479 1986  November      16      54     183      34      48     257
    ## 480 1986  December      16      54     183      34      48     257
    ## 481 1987   January      24      46     179      27      55     262
    ## 482 1987  February      24      46     179      27      55     262
    ## 483 1987     March      24      46     179      27      55     262
    ## 484 1987     April      24      46     179      27      55     262
    ## 485 1987       May      24      46     179      27      55     262
    ## 486 1987      June      24      46     179      27      55     262
    ## 487 1987      July      24      46     179      27      55     262
    ## 488 1987    August      24      46     179      27      55     262
    ## 489 1987 September      24      46     179      27      55     262
    ## 490 1987   October      24      46     179      27      55     262
    ## 491 1987  November      24      46     179      27      55     262
    ## 492 1987  December      24      46     179      27      55     262
    ## 493 1988   January      24      46     179      28      54     262
    ## 494 1988  February      24      46     179      28      54     262
    ## 495 1988     March      25      46     179      28      54     262
    ## 496 1988     April      24      46     179      28      54     262
    ## 497 1988       May      24      46     179      28      54     262
    ## 498 1988      June      24      46     179      28      54     262
    ## 499 1988      July      24      46     178      28      54     262
    ## 500 1988    August      24      46     178      28      54     262
    ## 501 1988 September      24      46     178      28      54     262
    ## 502 1988   October      24      46     178      28      54     262
    ## 503 1988  November      24      46     179      28      54     262
    ## 504 1988  December      24      46     179      28      54     262
    ## 505 1989   January      23      46     178      29      55     264
    ## 506 1989  February      23      46     178      29      55     264
    ## 507 1989     March      23      46     178      29      55     264
    ## 508 1989     April      23      46     178      29      55     264
    ## 509 1989       May      23      46     178      29      55     264
    ## 510 1989      June      23      46     178      29      55     262
    ## 511 1989      July      23      46     178      29      55     261
    ## 512 1989    August      23      46     178      29      55     261
    ## 513 1989 September      23      46     178      29      55     261
    ## 514 1989   October      23      46     178      29      55     261
    ## 515 1989  November      23      46     178      29      55     261
    ## 516 1989  December      23      46     178      29      55     261
    ## 517 1990   January      22      46     176      30      55     258
    ## 518 1990  February      22      46     176      30      55     258
    ## 519 1990     March      22      46     176      30      55     258
    ## 520 1990     April      22      46     176      30      55     258
    ## 521 1990       May      22      46     176      30      55     257
    ## 522 1990      June      22      46     176      30      56     257
    ## 523 1990      July      22      46     176      30      56     257
    ## 524 1990    August      22      46     176      30      56     257
    ## 525 1990 September      22      46     176      30      56     257
    ## 526 1990   October      22      46     176      30      56     258
    ## 527 1990  November      22      46     176      30      56     259
    ## 528 1990  December      22      46     176      30      56     259
    ## 529 1991   January      20      45     168      29      57     269
    ## 530 1991  February      20      45     168      29      57     269
    ## 531 1991     March      21      45     166      28      57     269
    ## 532 1991     April      21      45     166      28      57     269
    ## 533 1991       May      21      45     166      28      57     268
    ## 534 1991      June      21      45     166      28      57     268
    ## 535 1991      July      21      45     166      28      57     268
    ## 536 1991    August      21      45     166      29      57     268
    ## 537 1991 September      21      45     166      29      57     268
    ## 538 1991   October      21      45     166      29      57     268
    ## 539 1991  November      21      45     167      29      57     269
    ## 540 1991  December      21      45     167      29      57     269
    ## 541 1992   January      20      43     166      27      58     268
    ## 542 1992  February      20      43     166      27      58     268
    ## 543 1992     March      20      43     166      28      58     268
    ## 544 1992     April      20      43     166      28      58     268
    ## 545 1992       May      20      43     166      28      58     268
    ## 546 1992      June      20      43     166      28      58     268
    ## 547 1992      July      20      43     166      28      58     268
    ## 548 1992    August      20      43     166      28      58     268
    ## 549 1992 September      20      43     166      28      58     268
    ## 550 1992   October      20      43     166      28      59     268
    ## 551 1992  November      20      43     166      28      60     270
    ## 552 1992  December      20      43     166      28      60     270
    ## 553 1993   January      18      46     175      30      57     255
    ## 554 1993  February      18      46     175      30      57     255
    ## 555 1993     March      18      46     175      30      57     255
    ## 556 1993     April      18      46     175      30      57     256
    ## 557 1993       May      17      46     177      31      57     257
    ## 558 1993      June      17      46     178      31      57     258
    ## 559 1993      July      17      46     178      31      57     258
    ## 560 1993    August      17      46     178      31      57     258
    ## 561 1993 September      17      46     178      31      57     258
    ## 562 1993   October      17      46     178      31      57     258
    ## 563 1993  November      17      46     178      31      57     258
    ## 564 1993  December      17      46     178      31      57     258
    ## 565 1994   January      19      48     178      28      54     257
    ## 566 1994  February      19      48     178      28      54     257
    ## 567 1994     March      19      48     178      28      54     257
    ## 568 1994     April      19      48     178      28      54     256
    ## 569 1994       May      19      48     178      28      54     256
    ## 570 1994      June      19      48     178      28      54     256
    ## 571 1994      July      19      48     178      28      54     256
    ## 572 1994    August      19      48     178      28      54     256
    ## 573 1994 September      19      48     178      28      54     256
    ## 574 1994   October      19      48     178      28      54     256
    ## 575 1994  November      19      48     178      28      54     256
    ## 576 1994  December      19      48     178      28      54     256
    ## 577 1995   January      30      54     235      20      46     199
    ## 578 1995  February      30      54     235      20      46     199
    ## 579 1995     March      30      54     235      20      46     199
    ## 580 1995     April      30      54     235      20      46     199
    ## 581 1995       May      30      54     235      20      46     199
    ## 582 1995      June      30      54     235      20      46     199
    ## 583 1995      July      30      54     235      20      46     199
    ## 584 1995    August      30      54     235      20      46     199
    ## 585 1995 September      30      54     235      20      46     199
    ## 586 1995   October      30      54     235      20      46     199
    ## 587 1995  November      30      54     235      20      46     199
    ## 588 1995  December      30      54     235      20      46     199
    ## 589 1996   January      31      54     236      19      47     196
    ## 590 1996  February      31      54     236      19      47     196
    ## 591 1996     March      31      54     236      19      47     195
    ## 592 1996     April      31      54     236      19      47     196
    ## 593 1996       May      31      54     236      19      47     197
    ## 594 1996      June      31      54     236      19      47     198
    ## 595 1996      July      32      54     235      19      47     198
    ## 596 1996    August      32      54     235      19      47     198
    ## 597 1996 September      32      54     235      19      47     198
    ## 598 1996   October      32      54     235      19      47     198
    ## 599 1996  November      32      55     235      19      47     198
    ## 600 1996  December      32      55     235      19      47     198
    ## 601 1997   January      32      55     227      18      45     207
    ## 602 1997  February      32      55     227      18      45     207
    ## 603 1997     March      32      55     227      18      45     207
    ## 604 1997     April      32      55     227      18      45     207
    ## 605 1997       May      32      55     228      18      45     207
    ## 606 1997      June      32      55     228      18      45     207
    ## 607 1997      July      32      55     228      18      45     207
    ## 608 1997    August      33      55     228      18      45     207
    ## 609 1997 September      34      55     228      18      45     207
    ## 610 1997   October      34      55     228      18      45     207
    ## 611 1997  November      34      55     229      18      45     207
    ## 612 1997  December      34      55     229      18      45     207
    ## 613 1998   January      32      55     227      18      45     203
    ## 614 1998  February      32      55     227      18      45     203
    ## 615 1998     March      32      55     227      18      45     204
    ## 616 1998     April      32      55     227      18      45     205
    ## 617 1998       May      32      55     227      18      45     205
    ## 618 1998      June      32      55     227      18      45     206
    ## 619 1998      July      32      55     228      18      45     206
    ## 620 1998    August      32      55     228      18      45     206
    ## 621 1998 September      32      55     228      18      45     206
    ## 622 1998   October      32      55     228      18      45     206
    ## 623 1998  November      32      55     228      18      45     206
    ## 624 1998  December      32      55     228      18      45     206
    ## 625 1999   January      31      55     223      17      45     210
    ## 626 1999  February      31      55     223      17      45     210
    ## 627 1999     March      31      55     222      17      45     210
    ## 628 1999     April      31      55     222      17      45     210
    ## 629 1999       May      31      55     222      17      45     210
    ## 630 1999      June      31      55     223      17      45     210
    ## 631 1999      July      31      55     223      17      45     210
    ## 632 1999    August      31      55     223      17      45     210
    ## 633 1999 September      31      55     223      17      45     210
    ## 634 1999   October      31      55     223      17      45     210
    ## 635 1999  November      31      56     223      17      45     211
    ## 636 1999  December      31      56     223      17      45     211
    ## 637 2000   January      30      55     223      18      45     210
    ## 638 2000  February      30      55     223      18      45     210
    ## 639 2000     March      30      55     223      18      45     210
    ## 640 2000     April      30      55     223      18      45     210
    ## 641 2000       May      30      55     223      18      45     210
    ## 642 2000      June      30      55     223      18      45     210
    ## 643 2000      July      30      55     223      18      45     210
    ## 644 2000    August      30      55     223      18      46     210
    ## 645 2000 September      30      55     223      18      46     210
    ## 646 2000   October      30      55     223      18      46     210
    ## 647 2000  November      30      55     223      19      46     210
    ## 648 2000  December      30      55     223      19      46     210
    ## 649 2001   January      29      49     220      19      50     211
    ## 650 2001  February      29      49     220      19      50     211
    ## 651 2001     March      29      49     220      19      50     211
    ## 652 2001     April      29      49     220      19      50     210
    ## 653 2001       May      29      49     220      19      50     210
    ## 654 2001      June      29      49     221      19      50     210
    ## 655 2001      July      29      49     222      19      50     210
    ## 656 2001    August      29      49     222      19      50     210
    ## 657 2001 September      29      49     222      19      50     210
    ## 658 2001   October      30      49     222      19      50     210
    ## 659 2001  November      30      49     223      19      50     211
    ## 660 2001  December      30      49     223      19      50     211
    ## 661 2002   January      27      50     221      21      50     211
    ## 662 2002  February      27      50     221      21      50     211
    ## 663 2002     March      27      50     222      21      50     211
    ## 664 2002     April      27      50     222      21      50     211
    ## 665 2002       May      27      50     222      21      50     211
    ## 666 2002      June      27      50     222      21      50     211
    ## 667 2002      July      27      50     222      21      50     211
    ## 668 2002    August      27      50     222      21      50     211
    ## 669 2002 September      27      50     222      21      50     211
    ## 670 2002   October      27      50     222      21      50     211
    ## 671 2002  November      27      50     222      21      50     211
    ## 672 2002  December      27      50     222      21      50     211
    ## 673 2003   January      26      51     231      24      48     203
    ## 674 2003  February      26      51     231      24      48     203
    ## 675 2003     March      26      51     231      24      48     203
    ## 676 2003     April      26      51     231      24      48     203
    ## 677 2003       May      26      51     231      24      48     203
    ## 678 2003      June      26      51     231      24      48     203
    ## 679 2003      July      26      51     231      24      48     203
    ## 680 2003    August      26      51     231      24      48     203
    ## 681 2003 September      26      51     231      25      48     203
    ## 682 2003   October      26      51     231      25      48     203
    ## 683 2003  November      27      51     231      25      48     203
    ## 684 2003  December      27      51     231      25      48     203
    ## 685 2004   January      28      51     229      22      48     203
    ## 686 2004  February      28      51     229      22      48     203
    ## 687 2004     March      28      51     229      22      48     204
    ## 688 2004     April      28      51     229      22      48     204
    ## 689 2004       May      28      51     229      22      48     204
    ## 690 2004      June      28      51     229      22      48     204
    ## 691 2004      July      29      51     229      22      48     204
    ## 692 2004    August      29      51     229      22      48     205
    ## 693 2004 September      29      51     229      22      48     205
    ## 694 2004   October      29      51     229      22      48     205
    ## 695 2004  November      29      51     229      23      48     205
    ## 696 2004  December      29      51     229      23      48     205
    ## 697 2005   January      28      54     232      22      45     201
    ## 698 2005  February      28      54     232      22      45     201
    ## 699 2005     March      28      54     232      22      45     202
    ## 700 2005     April      28      54     232      22      45     202
    ## 701 2005       May      28      54     231      22      45     202
    ## 702 2005      June      28      54     231      22      45     202
    ## 703 2005      July      28      54     231      22      45     202
    ## 704 2005    August      28      54     231      22      45     202
    ## 705 2005 September      28      54     232      22      45     202
    ## 706 2005   October      28      54     232      22      45     202
    ## 707 2005  November      28      54     232      22      45     202
    ## 708 2005  December      28      54     232      22      45     202
    ## 709 2006   January      28      54     231      22      45     201
    ## 710 2006  February      28      54     231      22      45     201
    ## 711 2006     March      28      54     231      22      45     201
    ## 712 2006     April      28      54     231      22      45     201
    ## 713 2006       May      28      54     231      22      45     201
    ## 714 2006      June      28      54     231      22      45     201
    ## 715 2006      July      28      54     231      22      45     201
    ## 716 2006    August      28      54     231      22      45     201
    ## 717 2006 September      28      54     231      22      45     201
    ## 718 2006   October      28      54     231      22      45     201
    ## 719 2006  November      28      54     232      22      45     202
    ## 720 2006  December      28      54     232      22      45     202
    ## 721 2007   January      22      48     201      28      50     233
    ## 722 2007  February      22      48     201      28      50     233
    ## 723 2007     March      22      48     201      28      50     233
    ## 724 2007     April      22      48     201      28      50     233
    ## 725 2007       May      22      48     201      28      50     232
    ## 726 2007      June      22      47     201      28      50     232
    ## 727 2007      July      22      48     201      28      50     232
    ## 728 2007    August      22      48     202      28      50     232
    ## 729 2007 September      22      48     202      28      50     233
    ## 730 2007   October      22      48     202      28      50     233
    ## 731 2007  November      22      48     202      28      50     234
    ## 732 2007  December      22      48     202      28      50     234
    ## 733 2008   January      22      48     198      28      50     231
    ## 734 2008  February      22      48     198      28      50     231
    ## 735 2008     March      22      48     198      28      50     233
    ## 736 2008     April      22      48     198      28      50     234
    ## 737 2008       May      22      48     199      28      50     235
    ## 738 2008      June      22      48     199      28      50     235
    ## 739 2008      July      22      48     199      28      50     236
    ## 740 2008    August      22      48     199      28      50     236
    ## 741 2008 September      22      48     199      28      50     236
    ## 742 2008   October      22      48     199      28      50     236
    ## 743 2008  November      22      48     199      28      50     236
    ## 744 2008  December      22      48     199      28      50     236
    ## 745 2009   January      22      40     179      28      57     254
    ## 746 2009  February      22      40     179      28      57     254
    ## 747 2009     March      22      40     179      28      57     253
    ## 748 2009     April      22      40     179      28      57     254
    ## 749 2009       May      22      40     179      28      57     255
    ## 750 2009      June      22      40     179      28      57     255
    ## 751 2009      July      22      40     179      28      58     254
    ## 752 2009    August      24      40     179      28      58     255
    ## 753 2009 September      24      41     179      28      58     255
    ## 754 2009   October      24      41     179      28      59     255
    ## 755 2009  November      24      41     179      28      59     257
    ## 756 2009  December      24      41     179      28      59     257
    ## 757 2010   January      24      41     178      26      57     255
    ## 758 2010  February      24      41     178      26      57     255
    ## 759 2010     March      24      41     178      26      57     253
    ## 760 2010     April      24      41     177      26      57     254
    ## 761 2010       May      24      41     177      26      57     254
    ## 762 2010      June      24      41     178      26      57     255
    ## 763 2010      July      24      41     178      26      56     255
    ## 764 2010    August      24      41     178      26      57     255
    ## 765 2010 September      24      41     178      26      57     255
    ## 766 2010   October      24      41     178      26      57     255
    ## 767 2010  November      24      41     178      27      59     255
    ## 768 2010  December      24      41     178      27      59     255
    ## 769 2011   January      29      47     241      21      51     193
    ## 770 2011  February      29      47     241      21      51     193
    ## 771 2011     March      29      47     241      21      51     192
    ## 772 2011     April      29      47     241      21      51     192
    ## 773 2011       May      29      47     240      21      51     192
    ## 774 2011      June      29      47     240      21      51     193
    ## 775 2011      July      29      47     240      21      51     192
    ## 776 2011    August      29      47     240      21      51     193
    ## 777 2011 September      29      47     242      21      51     193
    ## 778 2011   October      29      47     242      21      51     193
    ## 779 2011  November      29      47     242      21      51     193
    ## 780 2011  December      29      47     242      21      51     193
    ## 781 2012   January      29      47     242      21      51     192
    ## 782 2012  February      29      47     242      21      51     192
    ## 783 2012     March      29      47     242      21      51     191
    ## 784 2012     April      29      47     242      21      51     190
    ## 785 2012       May      29      47     242      21      51     190
    ## 786 2012      June      29      47     242      21      51     191
    ## 787 2012      July      29      47     242      21      51     191
    ## 788 2012    August      29      47     242      21      51     191
    ## 789 2012 September      29      47     242      21      51     191
    ## 790 2012   October      29      47     242      21      51     191
    ## 791 2012  November      29      47     243      21      51     194
    ## 792 2012  December      29      47     243      21      51     194
    ## 793 2013   January      30      45     232      20      53     200
    ## 794 2013  February      30      45     232      20      53     200
    ## 795 2013     March      30      45     232      20      53     200
    ## 796 2013     April      30      45     232      20      53     201
    ## 797 2013       May      30      45     233      20      53     201
    ## 798 2013      June      30      46     234      20      52     201
    ## 799 2013      July      30      46     234      20      52     201
    ## 800 2013    August      30      46     234      20      53     201
    ## 801 2013 September      30      46     234      20      53     201
    ## 802 2013   October      30      46     234      20      53     201
    ## 803 2013  November      30      46     234      20      54     201
    ## 804 2013  December      30      46     234      20      54     201
    ## 805 2014   January      29      45     232      21      53     200
    ## 806 2014  February      29      45     232      21      53     200
    ## 807 2014     March      29      45     233      21      53     199
    ## 808 2014     April      29      45     233      21      53     199
    ## 809 2014       May      29      45     233      21      53     199
    ## 810 2014      June      29      45     233      21      53     199
    ## 811 2014      July      29      45     234      21      53     199
    ## 812 2014    August      29      45     234      21      53     199
    ## 813 2014 September      29      45     234      21      53     199
    ## 814 2014   October      29      45     234      21      53     199
    ## 815 2014  November      29      45     235      21      53     201
    ## 816 2014  December      29      45     235      21      53     201
    ## 817 2015   January      31      54     245      18      44     188
    ## 818 2015  February      31      54     245      18      44     188
    ## 819 2015     March      31      54     245      18      44     188
    ## 820 2015     April      31      54     244      18      44     188
    ## 821 2015       May      31      54     245      18      44     188
    ## 822 2015      June      31      54     246      18      44     188
    ##     president
    ## 1         dem
    ## 2         dem
    ## 3         dem
    ## 4         dem
    ## 5         dem
    ## 6         dem
    ## 7         dem
    ## 8         dem
    ## 9         dem
    ## 10        dem
    ## 11        dem
    ## 12        dem
    ## 13        dem
    ## 14        dem
    ## 15        dem
    ## 16        dem
    ## 17        dem
    ## 18        dem
    ## 19        dem
    ## 20        dem
    ## 21        dem
    ## 22        dem
    ## 23        dem
    ## 24        dem
    ## 25        dem
    ## 26        dem
    ## 27        dem
    ## 28        dem
    ## 29        dem
    ## 30        dem
    ## 31        dem
    ## 32        dem
    ## 33        dem
    ## 34        dem
    ## 35        dem
    ## 36        dem
    ## 37        dem
    ## 38        dem
    ## 39        dem
    ## 40        dem
    ## 41        dem
    ## 42        dem
    ## 43        dem
    ## 44        dem
    ## 45        dem
    ## 46        dem
    ## 47        dem
    ## 48        dem
    ## 49        dem
    ## 50        dem
    ## 51        dem
    ## 52        dem
    ## 53        dem
    ## 54        dem
    ## 55        dem
    ## 56        dem
    ## 57        dem
    ## 58        dem
    ## 59        dem
    ## 60        dem
    ## 61        dem
    ## 62        dem
    ## 63        dem
    ## 64        dem
    ## 65        dem
    ## 66        dem
    ## 67        dem
    ## 68        dem
    ## 69        dem
    ## 70        dem
    ## 71        dem
    ## 72        dem
    ## 73        gop
    ## 74        gop
    ## 75        gop
    ## 76        gop
    ## 77        gop
    ## 78        gop
    ## 79        gop
    ## 80        gop
    ## 81        gop
    ## 82        gop
    ## 83        gop
    ## 84        gop
    ## 85        gop
    ## 86        gop
    ## 87        gop
    ## 88        gop
    ## 89        gop
    ## 90        gop
    ## 91        gop
    ## 92        gop
    ## 93        gop
    ## 94        gop
    ## 95        gop
    ## 96        gop
    ## 97        gop
    ## 98        gop
    ## 99        gop
    ## 100       gop
    ## 101       gop
    ## 102       gop
    ## 103       gop
    ## 104       gop
    ## 105       gop
    ## 106       gop
    ## 107       gop
    ## 108       gop
    ## 109       gop
    ## 110       gop
    ## 111       gop
    ## 112       gop
    ## 113       gop
    ## 114       gop
    ## 115       gop
    ## 116       gop
    ## 117       gop
    ## 118       gop
    ## 119       gop
    ## 120       gop
    ## 121       gop
    ## 122       gop
    ## 123       gop
    ## 124       gop
    ## 125       gop
    ## 126       gop
    ## 127       gop
    ## 128       gop
    ## 129       gop
    ## 130       gop
    ## 131       gop
    ## 132       gop
    ## 133       gop
    ## 134       gop
    ## 135       gop
    ## 136       gop
    ## 137       gop
    ## 138       gop
    ## 139       gop
    ## 140       gop
    ## 141       gop
    ## 142       gop
    ## 143       gop
    ## 144       gop
    ## 145       gop
    ## 146       gop
    ## 147       gop
    ## 148       gop
    ## 149       gop
    ## 150       gop
    ## 151       gop
    ## 152       gop
    ## 153       gop
    ## 154       gop
    ## 155       gop
    ## 156       gop
    ## 157       gop
    ## 158       gop
    ## 159       gop
    ## 160       gop
    ## 161       gop
    ## 162       gop
    ## 163       gop
    ## 164       gop
    ## 165       gop
    ## 166       gop
    ## 167       gop
    ## 168       gop
    ## 169       dem
    ## 170       dem
    ## 171       dem
    ## 172       dem
    ## 173       dem
    ## 174       dem
    ## 175       dem
    ## 176       dem
    ## 177       dem
    ## 178       dem
    ## 179       dem
    ## 180       dem
    ## 181       dem
    ## 182       dem
    ## 183       dem
    ## 184       dem
    ## 185       dem
    ## 186       dem
    ## 187       dem
    ## 188       dem
    ## 189       dem
    ## 190       dem
    ## 191       dem
    ## 192       dem
    ## 193       dem
    ## 194       dem
    ## 195       dem
    ## 196       dem
    ## 197       dem
    ## 198       dem
    ## 199       dem
    ## 200       dem
    ## 201       dem
    ## 202       dem
    ## 203       dem
    ## 204       dem
    ## 205       dem
    ## 206       dem
    ## 207       dem
    ## 208       dem
    ## 209       dem
    ## 210       dem
    ## 211       dem
    ## 212       dem
    ## 213       dem
    ## 214       dem
    ## 215       dem
    ## 216       dem
    ## 217       dem
    ## 218       dem
    ## 219       dem
    ## 220       dem
    ## 221       dem
    ## 222       dem
    ## 223       dem
    ## 224       dem
    ## 225       dem
    ## 226       dem
    ## 227       dem
    ## 228       dem
    ## 229       dem
    ## 230       dem
    ## 231       dem
    ## 232       dem
    ## 233       dem
    ## 234       dem
    ## 235       dem
    ## 236       dem
    ## 237       dem
    ## 238       dem
    ## 239       dem
    ## 240       dem
    ## 241       dem
    ## 242       dem
    ## 243       dem
    ## 244       dem
    ## 245       dem
    ## 246       dem
    ## 247       dem
    ## 248       dem
    ## 249       dem
    ## 250       dem
    ## 251       dem
    ## 252       dem
    ## 253       dem
    ## 254       dem
    ## 255       dem
    ## 256       dem
    ## 257       dem
    ## 258       dem
    ## 259       dem
    ## 260       dem
    ## 261       dem
    ## 262       dem
    ## 263       dem
    ## 264       dem
    ## 265       gop
    ## 266       gop
    ## 267       gop
    ## 268       gop
    ## 269       gop
    ## 270       gop
    ## 271       gop
    ## 272       gop
    ## 273       gop
    ## 274       gop
    ## 275       gop
    ## 276       gop
    ## 277       gop
    ## 278       gop
    ## 279       gop
    ## 280       gop
    ## 281       gop
    ## 282       gop
    ## 283       gop
    ## 284       gop
    ## 285       gop
    ## 286       gop
    ## 287       gop
    ## 288       gop
    ## 289       gop
    ## 290       gop
    ## 291       gop
    ## 292       gop
    ## 293       gop
    ## 294       gop
    ## 295       gop
    ## 296       gop
    ## 297       gop
    ## 298       gop
    ## 299       gop
    ## 300       gop
    ## 301       gop
    ## 302       gop
    ## 303       gop
    ## 304       gop
    ## 305       gop
    ## 306       gop
    ## 307       gop
    ## 308       gop
    ## 309       gop
    ## 310       gop
    ## 311       gop
    ## 312       gop
    ## 313       gop
    ## 314       gop
    ## 315       gop
    ## 316       gop
    ## 317       gop
    ## 318       gop
    ## 319       gop
    ## 320       gop
    ## 321       gop
    ## 322       gop
    ## 323       gop
    ## 324       gop
    ## 325       gop
    ## 326       gop
    ## 327       gop
    ## 328       gop
    ## 329       gop
    ## 330       gop
    ## 331       gop
    ## 332       gop
    ## 333       gop
    ## 334       gop
    ## 335       gop
    ## 336       gop
    ## 337       gop
    ## 338       gop
    ## 339       gop
    ## 340       gop
    ## 341       gop
    ## 342       gop
    ## 343       gop
    ## 344       gop
    ## 345       gop
    ## 346       gop
    ## 347       gop
    ## 348       gop
    ## 349       gop
    ## 350       gop
    ## 351       gop
    ## 352       gop
    ## 353       gop
    ## 354       gop
    ## 355       gop
    ## 356       gop
    ## 357       gop
    ## 358       gop
    ## 359       gop
    ## 360       gop
    ## 361       dem
    ## 362       dem
    ## 363       dem
    ## 364       dem
    ## 365       dem
    ## 366       dem
    ## 367       dem
    ## 368       dem
    ## 369       dem
    ## 370       dem
    ## 371       dem
    ## 372       dem
    ## 373       dem
    ## 374       dem
    ## 375       dem
    ## 376       dem
    ## 377       dem
    ## 378       dem
    ## 379       dem
    ## 380       dem
    ## 381       dem
    ## 382       dem
    ## 383       dem
    ## 384       dem
    ## 385       dem
    ## 386       dem
    ## 387       dem
    ## 388       dem
    ## 389       dem
    ## 390       dem
    ## 391       dem
    ## 392       dem
    ## 393       dem
    ## 394       dem
    ## 395       dem
    ## 396       dem
    ## 397       dem
    ## 398       dem
    ## 399       dem
    ## 400       dem
    ## 401       dem
    ## 402       dem
    ## 403       dem
    ## 404       dem
    ## 405       dem
    ## 406       dem
    ## 407       dem
    ## 408       dem
    ## 409       gop
    ## 410       gop
    ## 411       gop
    ## 412       gop
    ## 413       gop
    ## 414       gop
    ## 415       gop
    ## 416       gop
    ## 417       gop
    ## 418       gop
    ## 419       gop
    ## 420       gop
    ## 421       gop
    ## 422       gop
    ## 423       gop
    ## 424       gop
    ## 425       gop
    ## 426       gop
    ## 427       gop
    ## 428       gop
    ## 429       gop
    ## 430       gop
    ## 431       gop
    ## 432       gop
    ## 433       gop
    ## 434       gop
    ## 435       gop
    ## 436       gop
    ## 437       gop
    ## 438       gop
    ## 439       gop
    ## 440       gop
    ## 441       gop
    ## 442       gop
    ## 443       gop
    ## 444       gop
    ## 445       gop
    ## 446       gop
    ## 447       gop
    ## 448       gop
    ## 449       gop
    ## 450       gop
    ## 451       gop
    ## 452       gop
    ## 453       gop
    ## 454       gop
    ## 455       gop
    ## 456       gop
    ## 457       gop
    ## 458       gop
    ## 459       gop
    ## 460       gop
    ## 461       gop
    ## 462       gop
    ## 463       gop
    ## 464       gop
    ## 465       gop
    ## 466       gop
    ## 467       gop
    ## 468       gop
    ## 469       gop
    ## 470       gop
    ## 471       gop
    ## 472       gop
    ## 473       gop
    ## 474       gop
    ## 475       gop
    ## 476       gop
    ## 477       gop
    ## 478       gop
    ## 479       gop
    ## 480       gop
    ## 481       gop
    ## 482       gop
    ## 483       gop
    ## 484       gop
    ## 485       gop
    ## 486       gop
    ## 487       gop
    ## 488       gop
    ## 489       gop
    ## 490       gop
    ## 491       gop
    ## 492       gop
    ## 493       gop
    ## 494       gop
    ## 495       gop
    ## 496       gop
    ## 497       gop
    ## 498       gop
    ## 499       gop
    ## 500       gop
    ## 501       gop
    ## 502       gop
    ## 503       gop
    ## 504       gop
    ## 505       gop
    ## 506       gop
    ## 507       gop
    ## 508       gop
    ## 509       gop
    ## 510       gop
    ## 511       gop
    ## 512       gop
    ## 513       gop
    ## 514       gop
    ## 515       gop
    ## 516       gop
    ## 517       gop
    ## 518       gop
    ## 519       gop
    ## 520       gop
    ## 521       gop
    ## 522       gop
    ## 523       gop
    ## 524       gop
    ## 525       gop
    ## 526       gop
    ## 527       gop
    ## 528       gop
    ## 529       gop
    ## 530       gop
    ## 531       gop
    ## 532       gop
    ## 533       gop
    ## 534       gop
    ## 535       gop
    ## 536       gop
    ## 537       gop
    ## 538       gop
    ## 539       gop
    ## 540       gop
    ## 541       gop
    ## 542       gop
    ## 543       gop
    ## 544       gop
    ## 545       gop
    ## 546       gop
    ## 547       gop
    ## 548       gop
    ## 549       gop
    ## 550       gop
    ## 551       gop
    ## 552       gop
    ## 553       dem
    ## 554       dem
    ## 555       dem
    ## 556       dem
    ## 557       dem
    ## 558       dem
    ## 559       dem
    ## 560       dem
    ## 561       dem
    ## 562       dem
    ## 563       dem
    ## 564       dem
    ## 565       dem
    ## 566       dem
    ## 567       dem
    ## 568       dem
    ## 569       dem
    ## 570       dem
    ## 571       dem
    ## 572       dem
    ## 573       dem
    ## 574       dem
    ## 575       dem
    ## 576       dem
    ## 577       dem
    ## 578       dem
    ## 579       dem
    ## 580       dem
    ## 581       dem
    ## 582       dem
    ## 583       dem
    ## 584       dem
    ## 585       dem
    ## 586       dem
    ## 587       dem
    ## 588       dem
    ## 589       dem
    ## 590       dem
    ## 591       dem
    ## 592       dem
    ## 593       dem
    ## 594       dem
    ## 595       dem
    ## 596       dem
    ## 597       dem
    ## 598       dem
    ## 599       dem
    ## 600       dem
    ## 601       dem
    ## 602       dem
    ## 603       dem
    ## 604       dem
    ## 605       dem
    ## 606       dem
    ## 607       dem
    ## 608       dem
    ## 609       dem
    ## 610       dem
    ## 611       dem
    ## 612       dem
    ## 613       dem
    ## 614       dem
    ## 615       dem
    ## 616       dem
    ## 617       dem
    ## 618       dem
    ## 619       dem
    ## 620       dem
    ## 621       dem
    ## 622       dem
    ## 623       dem
    ## 624       dem
    ## 625       dem
    ## 626       dem
    ## 627       dem
    ## 628       dem
    ## 629       dem
    ## 630       dem
    ## 631       dem
    ## 632       dem
    ## 633       dem
    ## 634       dem
    ## 635       dem
    ## 636       dem
    ## 637       dem
    ## 638       dem
    ## 639       dem
    ## 640       dem
    ## 641       dem
    ## 642       dem
    ## 643       dem
    ## 644       dem
    ## 645       dem
    ## 646       dem
    ## 647       dem
    ## 648       dem
    ## 649       gop
    ## 650       gop
    ## 651       gop
    ## 652       gop
    ## 653       gop
    ## 654       gop
    ## 655       gop
    ## 656       gop
    ## 657       gop
    ## 658       gop
    ## 659       gop
    ## 660       gop
    ## 661       gop
    ## 662       gop
    ## 663       gop
    ## 664       gop
    ## 665       gop
    ## 666       gop
    ## 667       gop
    ## 668       gop
    ## 669       gop
    ## 670       gop
    ## 671       gop
    ## 672       gop
    ## 673       gop
    ## 674       gop
    ## 675       gop
    ## 676       gop
    ## 677       gop
    ## 678       gop
    ## 679       gop
    ## 680       gop
    ## 681       gop
    ## 682       gop
    ## 683       gop
    ## 684       gop
    ## 685       gop
    ## 686       gop
    ## 687       gop
    ## 688       gop
    ## 689       gop
    ## 690       gop
    ## 691       gop
    ## 692       gop
    ## 693       gop
    ## 694       gop
    ## 695       gop
    ## 696       gop
    ## 697       gop
    ## 698       gop
    ## 699       gop
    ## 700       gop
    ## 701       gop
    ## 702       gop
    ## 703       gop
    ## 704       gop
    ## 705       gop
    ## 706       gop
    ## 707       gop
    ## 708       gop
    ## 709       gop
    ## 710       gop
    ## 711       gop
    ## 712       gop
    ## 713       gop
    ## 714       gop
    ## 715       gop
    ## 716       gop
    ## 717       gop
    ## 718       gop
    ## 719       gop
    ## 720       gop
    ## 721       gop
    ## 722       gop
    ## 723       gop
    ## 724       gop
    ## 725       gop
    ## 726       gop
    ## 727       gop
    ## 728       gop
    ## 729       gop
    ## 730       gop
    ## 731       gop
    ## 732       gop
    ## 733       gop
    ## 734       gop
    ## 735       gop
    ## 736       gop
    ## 737       gop
    ## 738       gop
    ## 739       gop
    ## 740       gop
    ## 741       gop
    ## 742       gop
    ## 743       gop
    ## 744       gop
    ## 745       dem
    ## 746       dem
    ## 747       dem
    ## 748       dem
    ## 749       dem
    ## 750       dem
    ## 751       dem
    ## 752       dem
    ## 753       dem
    ## 754       dem
    ## 755       dem
    ## 756       dem
    ## 757       dem
    ## 758       dem
    ## 759       dem
    ## 760       dem
    ## 761       dem
    ## 762       dem
    ## 763       dem
    ## 764       dem
    ## 765       dem
    ## 766       dem
    ## 767       dem
    ## 768       dem
    ## 769       dem
    ## 770       dem
    ## 771       dem
    ## 772       dem
    ## 773       dem
    ## 774       dem
    ## 775       dem
    ## 776       dem
    ## 777       dem
    ## 778       dem
    ## 779       dem
    ## 780       dem
    ## 781       dem
    ## 782       dem
    ## 783       dem
    ## 784       dem
    ## 785       dem
    ## 786       dem
    ## 787       dem
    ## 788       dem
    ## 789       dem
    ## 790       dem
    ## 791       dem
    ## 792       dem
    ## 793       dem
    ## 794       dem
    ## 795       dem
    ## 796       dem
    ## 797       dem
    ## 798       dem
    ## 799       dem
    ## 800       dem
    ## 801       dem
    ## 802       dem
    ## 803       dem
    ## 804       dem
    ## 805       dem
    ## 806       dem
    ## 807       dem
    ## 808       dem
    ## 809       dem
    ## 810       dem
    ## 811       dem
    ## 812       dem
    ## 813       dem
    ## 814       dem
    ## 815       dem
    ## 816       dem
    ## 817       dem
    ## 818       dem
    ## 819       dem
    ## 820       dem
    ## 821       dem
    ## 822       dem

``` r
# import and clean S&P closing data 

snp_df =
  read.csv("./data/fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names(dat = .) %>%
  rename(.data = ., closing_values = close) %>%
  separate(., date, into = c("month", "day", "year")) %>% 
  select(.data = ., year, everything(), -day) %>%
  mutate(.data = ., month = month.name[as.numeric(month)])

snp_df
```

    ##     year     month closing_values
    ## 1   2015      July        2079.65
    ## 2   2015      June        2063.11
    ## 3   2015       May        2107.39
    ## 4   2015     April        2085.51
    ## 5   2015     March        2067.89
    ## 6   2015  February        2104.50
    ## 7   2015   January        1994.99
    ## 8   2014  December        2058.90
    ## 9   2014  November        2067.56
    ## 10  2014   October        2018.05
    ## 11  2014 September        1972.29
    ## 12  2014    August        2003.37
    ## 13  2014      July        1930.67
    ## 14  2014      June        1960.23
    ## 15  2014       May        1923.57
    ## 16  2014     April        1883.95
    ## 17  2014     March        1872.34
    ## 18  2014  February        1859.45
    ## 19  2014   January        1782.59
    ## 20  2013  December        1848.36
    ## 21  2013  November        1805.81
    ## 22  2013   October        1756.54
    ## 23  2013 September        1681.55
    ## 24  2013    August        1632.97
    ## 25  2013      July        1685.73
    ## 26  2013      June        1606.28
    ## 27  2013       May        1630.74
    ## 28  2013     April        1597.57
    ## 29  2013     March        1569.19
    ## 30  2013  February        1514.68
    ## 31  2013   January        1498.11
    ## 32  2012  December        1426.19
    ## 33  2012  November        1416.18
    ## 34  2012   October        1412.16
    ## 35  2012 September        1440.67
    ## 36  2012    August        1406.58
    ## 37  2012      July        1379.32
    ## 38  2012      June        1362.16
    ## 39  2012       May        1310.33
    ## 40  2012     April        1397.91
    ## 41  2012     March        1408.47
    ## 42  2012  February        1365.68
    ## 43  2012   January        1312.41
    ## 44  2011  December        1257.60
    ## 45  2011  November        1246.96
    ## 46  2011   October        1253.30
    ## 47  2011 September        1131.42
    ## 48  2011    August        1218.89
    ## 49  2011      July        1292.28
    ## 50  2011      June        1320.64
    ## 51  2011       May        1345.20
    ## 52  2011     April        1363.61
    ## 53  2011     March        1325.83
    ## 54  2011  February        1327.22
    ## 55  2011   January        1286.12
    ## 56  2010  December        1257.64
    ## 57  2010  November        1180.55
    ## 58  2010   October        1183.26
    ## 59  2010 September        1141.20
    ## 60  2010    August        1049.33
    ## 61  2010      July        1101.60
    ## 62  2010      June        1030.71
    ## 63  2010       May        1089.41
    ## 64  2010     April        1186.69
    ## 65  2010     March        1169.43
    ## 66  2010  February        1104.49
    ## 67  2010   January        1073.87
    ## 68  2009  December        1115.10
    ## 69  2009  November        1095.63
    ## 70  2009   October        1036.19
    ## 71  2009 September        1057.08
    ## 72  2009    August        1020.62
    ## 73  2009      July         987.48
    ## 74  2009      June         919.32
    ## 75  2009       May         919.14
    ## 76  2009     April         872.81
    ## 77  2009     March         797.87
    ## 78  2009  February         735.09
    ## 79  2009   January         825.88
    ## 80  2008  December         903.25
    ## 81  2008  November         896.24
    ## 82  2008   October         968.75
    ## 83  2008 September        1166.36
    ## 84  2008    August        1282.83
    ## 85  2008      July        1267.38
    ## 86  2008      June        1280.00
    ## 87  2008       May        1400.38
    ## 88  2008     April        1385.59
    ## 89  2008     March        1322.70
    ## 90  2008  February        1330.63
    ## 91  2008   January        1378.55
    ## 92  2007  December        1468.36
    ## 93  2007  November        1481.14
    ## 94  2007   October        1549.38
    ## 95  2007 September        1526.75
    ## 96  2007    August        1473.99
    ## 97  2007      July        1455.27
    ## 98  2007      June        1503.35
    ## 99  2007       May        1530.62
    ## 100 2007     April        1482.37
    ## 101 2007     March        1420.86
    ## 102 2007  February        1406.82
    ## 103 2007   January        1438.24
    ## 104 2006  December        1418.30
    ## 105 2006  November        1400.63
    ## 106 2006   October        1377.94
    ## 107 2006 September        1335.85
    ## 108 2006    August        1303.82
    ## 109 2006      July        1276.66
    ## 110 2006      June        1270.20
    ## 111 2006       May        1270.09
    ## 112 2006     April        1310.61
    ## 113 2006     March        1294.87
    ## 114 2006  February        1280.66
    ## 115 2006   January        1280.08
    ## 116 2005  December        1248.29
    ## 117 2005  November        1249.48
    ## 118 2005   October        1207.01
    ## 119 2005 September        1228.81
    ## 120 2005    August        1220.33
    ## 121 2005      July        1234.18
    ## 122 2005      June        1191.33
    ## 123 2005       May        1191.50
    ## 124 2005     April        1156.85
    ## 125 2005     March        1180.59
    ## 126 2005  February        1203.60
    ## 127 2005   January        1181.27
    ## 128 2004  December        1211.92
    ## 129 2004  November        1173.82
    ## 130 2004   October        1130.20
    ## 131 2004 September        1114.58
    ## 132 2004    August        1104.24
    ## 133 2004      July        1101.72
    ## 134 2004      June        1140.84
    ## 135 2004       May        1120.68
    ## 136 2004     April        1107.30
    ## 137 2004     March        1126.21
    ## 138 2004  February        1144.94
    ## 139 2004   January        1131.13
    ## 140 2003  December        1111.92
    ## 141 2003  November        1058.20
    ## 142 2003   October        1050.71
    ## 143 2003 September         995.97
    ## 144 2003    August        1008.01
    ## 145 2003      July         990.31
    ## 146 2003      June         974.50
    ## 147 2003       May         963.59
    ## 148 2003     April         916.92
    ## 149 2003     March         848.18
    ## 150 2003  February         841.15
    ## 151 2003   January         855.70
    ## 152 2002  December         879.82
    ## 153 2002  November         936.31
    ## 154 2002   October         885.76
    ## 155 2002 September         815.28
    ## 156 2002    August         916.07
    ## 157 2002      July         911.62
    ## 158 2002      June         989.82
    ## 159 2002       May        1067.14
    ## 160 2002     April        1076.92
    ## 161 2002     March        1147.39
    ## 162 2002  February        1106.73
    ## 163 2002   January        1130.20
    ## 164 2001  December        1148.08
    ## 165 2001  November        1139.45
    ## 166 2001   October        1059.78
    ## 167 2001 September        1040.94
    ## 168 2001    August        1133.58
    ## 169 2001      July        1211.23
    ## 170 2001      June        1224.38
    ## 171 2001       May        1255.82
    ## 172 2001     April        1249.46
    ## 173 2001     March        1160.33
    ## 174 2001  February        1239.94
    ## 175 2001   January        1366.01
    ## 176 2000  December        1320.28
    ## 177 2000  November        1314.95
    ## 178 2000   October        1429.40
    ## 179 2000 September        1436.51
    ## 180 2000    August        1517.68
    ## 181 2000      July        1430.83
    ## 182 2000      June        1454.60
    ## 183 2000       May        1420.60
    ## 184 2000     April        1452.43
    ## 185 2000     March        1498.58
    ## 186 2000  February        1366.42
    ## 187 2000   January        1394.46
    ## 188 1999  December        1469.25
    ## 189 1999  November        1388.91
    ## 190 1999   October        1362.93
    ## 191 1999 September        1282.71
    ## 192 1999    August        1320.41
    ## 193 1999      July        1328.72
    ## 194 1999      June        1372.71
    ## 195 1999       May        1301.84
    ## 196 1999     April        1335.18
    ## 197 1999     March        1286.37
    ## 198 1999  February        1238.33
    ## 199 1999   January        1279.64
    ## 200 1998  December        1229.23
    ## 201 1998  November        1163.63
    ## 202 1998   October        1098.67
    ## 203 1998 September        1017.01
    ## 204 1998    August         957.28
    ## 205 1998      July        1120.67
    ## 206 1998      June        1133.84
    ## 207 1998       May        1090.82
    ## 208 1998     April        1111.75
    ## 209 1998     March        1101.75
    ## 210 1998  February        1049.34
    ## 211 1998   January         980.28
    ## 212 1997  December         970.43
    ## 213 1997  November         955.40
    ## 214 1997   October         914.62
    ## 215 1997 September         947.28
    ## 216 1997    August         899.47
    ## 217 1997      July         954.31
    ## 218 1997      June         885.14
    ## 219 1997       May         848.28
    ## 220 1997     April         801.34
    ## 221 1997     March         757.12
    ## 222 1997  February         790.82
    ## 223 1997   January         786.16
    ## 224 1996  December         740.74
    ## 225 1996  November         757.02
    ## 226 1996   October         705.27
    ## 227 1996 September         687.33
    ## 228 1996    August         651.99
    ## 229 1996      July         639.95
    ## 230 1996      June         670.63
    ## 231 1996       May         669.12
    ## 232 1996     April         654.17
    ## 233 1996     March         645.50
    ## 234 1996  February         640.43
    ## 235 1996   January         636.02
    ## 236 1995  December         615.93
    ## 237 1995  November         605.37
    ## 238 1995   October         581.50
    ## 239 1995 September         584.41
    ## 240 1995    August         561.88
    ## 241 1995      July         562.06
    ## 242 1995      June         544.75
    ## 243 1995       May         533.40
    ## 244 1995     April         514.71
    ## 245 1995     March         500.71
    ## 246 1995  February         487.39
    ## 247 1995   January         470.42
    ## 248 1994  December         459.27
    ## 249 1994  November         453.69
    ## 250 1994   October         472.35
    ## 251 1994 September         462.71
    ## 252 1994    August         475.49
    ## 253 1994      July         458.26
    ## 254 1994      June         444.27
    ## 255 1994       May         456.50
    ## 256 1994     April         450.91
    ## 257 1994     March         445.77
    ## 258 1994  February         467.14
    ## 259 1994   January         481.61
    ## 260 1993  December         466.45
    ## 261 1993  November         461.79
    ## 262 1993   October         467.83
    ## 263 1993 September         458.93
    ## 264 1993    August         463.56
    ## 265 1993      July         448.13
    ## 266 1993      June         450.53
    ## 267 1993       May         450.19
    ## 268 1993     April         440.19
    ## 269 1993     March         451.67
    ## 270 1993  February         443.38
    ## 271 1993   January         438.78
    ## 272 1992  December         435.71
    ## 273 1992  November         431.35
    ## 274 1992   October         418.68
    ## 275 1992 September         417.80
    ## 276 1992    August         414.03
    ## 277 1992      July         424.21
    ## 278 1992      June         408.14
    ## 279 1992       May         415.35
    ## 280 1992     April         414.95
    ## 281 1992     March         403.69
    ## 282 1992  February         412.70
    ## 283 1992   January         408.78
    ## 284 1991  December         417.09
    ## 285 1991  November         375.22
    ## 286 1991   October         392.45
    ## 287 1991 September         387.86
    ## 288 1991    August         395.43
    ## 289 1991      July         387.81
    ## 290 1991      June         371.16
    ## 291 1991       May         389.83
    ## 292 1991     April         375.34
    ## 293 1991     March         375.22
    ## 294 1991  February         367.07
    ## 295 1991   January         343.93
    ## 296 1990  December         330.22
    ## 297 1990  November         322.22
    ## 298 1990   October         304.00
    ## 299 1990 September         306.05
    ## 300 1990    August         322.56
    ## 301 1990      July         356.15
    ## 302 1990      June         358.02
    ## 303 1990       May         361.23
    ## 304 1990     April         330.80
    ## 305 1990     March         339.94
    ## 306 1990  February         331.89
    ## 307 1990   January         329.08
    ## 308 1989  December         353.40
    ## 309 1989  November         345.99
    ## 310 1989   October         340.36
    ## 311 1989 September         349.15
    ## 312 1989    August         351.45
    ## 313 1989      July         346.08
    ## 314 1989      June         317.98
    ## 315 1989       May         320.52
    ## 316 1989     April         309.64
    ## 317 1989     March         294.87
    ## 318 1989  February         288.86
    ## 319 1989   January         297.47
    ## 320 1988  December         277.72
    ## 321 1988  November         273.70
    ## 322 1988   October         278.97
    ## 323 1988 September         271.91
    ## 324 1988    August         261.52
    ## 325 1988      July         272.02
    ## 326 1988      June         273.50
    ## 327 1988       May         262.16
    ## 328 1988     April         261.33
    ## 329 1988     March         258.89
    ## 330 1988  February         267.82
    ## 331 1988   January         257.07
    ## 332 1987  December         247.08
    ## 333 1987  November         230.30
    ## 334 1987   October         251.79
    ## 335 1987 September         321.83
    ## 336 1987    August         329.80
    ## 337 1987      July         318.66
    ## 338 1987      June         304.00
    ## 339 1987       May         290.10
    ## 340 1987     April         288.36
    ## 341 1987     March         291.70
    ## 342 1987  February         284.20
    ## 343 1987   January         274.08
    ## 344 1986  December         242.17
    ## 345 1986  November         249.22
    ## 346 1986   October         243.98
    ## 347 1986 September         231.32
    ## 348 1986    August         252.93
    ## 349 1986      July         236.12
    ## 350 1986      June         250.84
    ## 351 1986       May         247.35
    ## 352 1986     April         235.52
    ## 353 1986     March         238.90
    ## 354 1986  February         226.92
    ## 355 1986   January         211.78
    ## 356 1985  December         211.28
    ## 357 1985  November         202.17
    ## 358 1985   October         189.82
    ## 359 1985 September         182.08
    ## 360 1985    August         188.63
    ## 361 1985      July         190.92
    ## 362 1985      June         191.85
    ## 363 1985       May         189.55
    ## 364 1985     April         179.83
    ## 365 1985     March         180.66
    ## 366 1985  February         181.18
    ## 367 1985   January         179.63
    ## 368 1984  December         167.24
    ## 369 1984  November         163.58
    ## 370 1984   October         166.09
    ## 371 1984 September         166.10
    ## 372 1984    August         166.68
    ## 373 1984      July         150.66
    ## 374 1984      June         153.18
    ## 375 1984       May         150.55
    ## 376 1984     April         160.05
    ## 377 1984     March         159.18
    ## 378 1984  February         157.06
    ## 379 1984   January         163.41
    ## 380 1983  December         164.93
    ## 381 1983  November         166.40
    ## 382 1983   October         163.55
    ## 383 1983 September         166.07
    ## 384 1983    August         164.40
    ## 385 1983      July         162.56
    ## 386 1983      June         167.64
    ## 387 1983       May         162.39
    ## 388 1983     April         164.43
    ## 389 1983     March         152.96
    ## 390 1983  February         148.06
    ## 391 1983   January         145.30
    ## 392 1982  December         140.64
    ## 393 1982  November         138.53
    ## 394 1982   October         133.72
    ## 395 1982 September         120.42
    ## 396 1982    August         119.51
    ## 397 1982      July         107.09
    ## 398 1982      June         109.61
    ## 399 1982       May         111.88
    ## 400 1982     April         116.44
    ## 401 1982     March         111.96
    ## 402 1982  February         113.11
    ## 403 1982   January         120.40
    ## 404 1981  December         122.55
    ## 405 1981  November         126.35
    ## 406 1981   October         121.89
    ## 407 1981 September         116.18
    ## 408 1981    August         122.79
    ## 409 1981      July         130.92
    ## 410 1981      June         131.21
    ## 411 1981       May         132.59
    ## 412 1981     April         132.81
    ## 413 1981     March         136.00
    ## 414 1981  February         131.27
    ## 415 1981   January         129.55
    ## 416 1980  December         135.76
    ## 417 1980  November         140.52
    ## 418 1980   October         127.47
    ## 419 1980 September         125.46
    ## 420 1980    August         122.38
    ## 421 1980      July         121.67
    ## 422 1980      June         114.24
    ## 423 1980       May         111.24
    ## 424 1980     April         106.29
    ## 425 1980     March         102.09
    ## 426 1980  February         113.66
    ## 427 1980   January         114.16
    ## 428 1979  December         107.94
    ## 429 1979  November         106.16
    ## 430 1979   October         101.82
    ## 431 1979 September         109.32
    ## 432 1979    August         109.32
    ## 433 1979      July         103.81
    ## 434 1979      June         102.91
    ## 435 1979       May          99.08
    ## 436 1979     April         101.76
    ## 437 1979     March         101.59
    ## 438 1979  February          96.28
    ## 439 1979   January          99.93
    ## 440 1978  December          96.11
    ## 441 1978  November          94.70
    ## 442 1978   October          93.15
    ## 443 1978 September         102.54
    ## 444 1978    August         103.29
    ## 445 1978      July         100.68
    ## 446 1978      June          95.53
    ## 447 1978       May          97.24
    ## 448 1978     April          96.83
    ## 449 1978     March          89.21
    ## 450 1978  February          87.04
    ## 451 1978   January          89.25
    ## 452 1977  December          95.10
    ## 453 1977  November          94.83
    ## 454 1977   October          92.34
    ## 455 1977 September          96.53
    ## 456 1977    August          96.77
    ## 457 1977      July          98.85
    ## 458 1977      June         100.48
    ## 459 1977       May          96.12
    ## 460 1977     April          98.44
    ## 461 1977     March          98.42
    ## 462 1977  February          99.82
    ## 463 1977   January         102.03
    ## 464 1976  December         107.46
    ## 465 1976  November         102.10
    ## 466 1976   October         102.90
    ## 467 1976 September         105.24
    ## 468 1976    August         102.91
    ## 469 1976      July         103.44
    ## 470 1976      June         104.28
    ## 471 1976       May         100.18
    ## 472 1976     April         101.64
    ## 473 1976     March         102.77
    ## 474 1976  February          99.71
    ## 475 1976   January         100.86
    ## 476 1975  December          90.19
    ## 477 1975  November          91.24
    ## 478 1975   October          89.04
    ## 479 1975 September          83.87
    ## 480 1975    August          86.88
    ## 481 1975      July          88.75
    ## 482 1975      June          95.19
    ## 483 1975       May          91.15
    ## 484 1975     April          87.30
    ## 485 1975     March          83.36
    ## 486 1975  February          81.59
    ## 487 1975   January          76.98
    ## 488 1974  December          68.56
    ## 489 1974  November          69.97
    ## 490 1974   October          73.90
    ## 491 1974 September          63.54
    ## 492 1974    August          72.15
    ## 493 1974      July          79.31
    ## 494 1974      June          86.00
    ## 495 1974       May          87.28
    ## 496 1974     April          90.31
    ## 497 1974     March          93.98
    ## 498 1974  February          96.22
    ## 499 1974   January          96.57
    ## 500 1973  December          97.55
    ## 501 1973  November          95.96
    ## 502 1973   October         108.29
    ## 503 1973 September         108.43
    ## 504 1973    August         104.25
    ## 505 1973      July         108.22
    ## 506 1973      June         104.26
    ## 507 1973       May         104.95
    ## 508 1973     April         106.97
    ## 509 1973     March         111.52
    ## 510 1973  February         111.68
    ## 511 1973   January         116.03
    ## 512 1972  December         118.05
    ## 513 1972  November         116.67
    ## 514 1972   October         111.58
    ## 515 1972 September         110.55
    ## 516 1972    August         111.09
    ## 517 1972      July         107.39
    ## 518 1972      June         107.14
    ## 519 1972       May         109.53
    ## 520 1972     April         107.67
    ## 521 1972     March         107.20
    ## 522 1972  February         106.57
    ## 523 1972   January         103.94
    ## 524 1971  December         102.09
    ## 525 1971  November          93.99
    ## 526 1971   October          94.23
    ## 527 1971 September          98.34
    ## 528 1971    August          99.03
    ## 529 1971      July          95.58
    ## 530 1971      June          98.70
    ## 531 1971       May          99.63
    ## 532 1971     April         103.95
    ## 533 1971     March         100.31
    ## 534 1971  February          96.75
    ## 535 1971   January          95.88
    ## 536 1970  December          92.15
    ## 537 1970  November          87.20
    ## 538 1970   October          83.25
    ## 539 1970 September          84.30
    ## 540 1970    August          81.52
    ## 541 1970      July          78.05
    ## 542 1970      June          72.72
    ## 543 1970       May          76.55
    ## 544 1970     April          81.52
    ## 545 1970     March          89.63
    ## 546 1970  February          89.50
    ## 547 1970   January          85.02
    ## 548 1969  December          92.06
    ## 549 1969  November          93.81
    ## 550 1969   October          97.12
    ## 551 1969 September          93.12
    ## 552 1969    August          95.51
    ## 553 1969      July          91.83
    ## 554 1969      June          97.71
    ## 555 1969       May         103.46
    ## 556 1969     April         103.69
    ## 557 1969     March         101.51
    ## 558 1969  February          98.13
    ## 559 1969   January         103.01
    ## 560 1968  December         103.86
    ## 561 1968  November         108.37
    ## 562 1968   October         103.41
    ## 563 1968 September         102.67
    ## 564 1968    August          98.86
    ## 565 1968      July          97.74
    ## 566 1968      June          99.58
    ## 567 1968       May          98.68
    ## 568 1968     April          97.46
    ## 569 1968     March          90.20
    ## 570 1968  February          89.36
    ## 571 1968   January          92.24
    ## 572 1967  December          96.47
    ## 573 1967  November          94.00
    ## 574 1967   October          93.30
    ## 575 1967 September          96.71
    ## 576 1967    August          93.64
    ## 577 1967      July          94.75
    ## 578 1967      June          90.64
    ## 579 1967       May          89.08
    ## 580 1967     April          94.01
    ## 581 1967     March          90.20
    ## 582 1967  February          86.78
    ## 583 1967   January          86.61
    ## 584 1966  December          80.33
    ## 585 1966  November          80.45
    ## 586 1966   October          80.20
    ## 587 1966 September          76.56
    ## 588 1966    August          77.10
    ## 589 1966      July          83.60
    ## 590 1966      June          84.74
    ## 591 1966       May          86.13
    ## 592 1966     April          91.06
    ## 593 1966     March          89.23
    ## 594 1966  February          91.22
    ## 595 1966   January          92.88
    ## 596 1965  December          92.43
    ## 597 1965  November          91.61
    ## 598 1965   October          92.42
    ## 599 1965 September          89.96
    ## 600 1965    August          87.17
    ## 601 1965      July          85.25
    ## 602 1965      June          84.12
    ## 603 1965       May          88.42
    ## 604 1965     April          89.11
    ## 605 1965     March          86.16
    ## 606 1965  February          87.43
    ## 607 1965   January          87.56
    ## 608 1964  December          84.75
    ## 609 1964  November          84.42
    ## 610 1964   October          84.86
    ## 611 1964 September          84.18
    ## 612 1964    August          81.83
    ## 613 1964      July          83.18
    ## 614 1964      June          81.69
    ## 615 1964       May          80.37
    ## 616 1964     April          79.46
    ## 617 1964     March          78.98
    ## 618 1964  February          77.80
    ## 619 1964   January          77.04
    ## 620 1963  December          75.02
    ## 621 1963  November          73.23
    ## 622 1963   October          74.01
    ## 623 1963 September          71.70
    ## 624 1963    August          72.50
    ## 625 1963      July          69.13
    ## 626 1963      June          69.37
    ## 627 1963       May          70.80
    ## 628 1963     April          69.80
    ## 629 1963     March          66.57
    ## 630 1963  February          64.29
    ## 631 1963   January          66.20
    ## 632 1962  December          63.10
    ## 633 1962  November          62.26
    ## 634 1962   October          56.52
    ## 635 1962 September          56.27
    ## 636 1962    August          59.12
    ## 637 1962      July          58.23
    ## 638 1962      June          54.75
    ## 639 1962       May          59.63
    ## 640 1962     April          65.24
    ## 641 1962     March          69.55
    ## 642 1962  February          69.96
    ## 643 1962   January          68.84
    ## 644 1961  December          71.55
    ## 645 1961  November          71.32
    ## 646 1961   October          68.62
    ## 647 1961 September          66.73
    ## 648 1961    August          68.07
    ## 649 1961      July          66.76
    ## 650 1961      June          64.64
    ## 651 1961       May          66.56
    ## 652 1961     April          65.31
    ## 653 1961     March          65.06
    ## 654 1961  February          63.44
    ## 655 1961   January          61.78
    ## 656 1960  December          58.11
    ## 657 1960  November          55.54
    ## 658 1960   October          53.39
    ## 659 1960 September          53.52
    ## 660 1960    August          56.96
    ## 661 1960      July          55.51
    ## 662 1960      June          56.92
    ## 663 1960       May          55.83
    ## 664 1960     April          54.37
    ## 665 1960     March          55.34
    ## 666 1960  February          56.12
    ## 667 1960   January          55.61
    ## 668 1959  December          59.89
    ## 669 1959  November          58.28
    ## 670 1959   October          57.52
    ## 671 1959 September          56.88
    ## 672 1959    August          59.60
    ## 673 1959      July          60.51
    ## 674 1959      June          58.47
    ## 675 1959       May          58.68
    ## 676 1959     April          57.59
    ## 677 1959     March          55.44
    ## 678 1959  February          55.41
    ## 679 1959   January          55.45
    ## 680 1958  December          55.21
    ## 681 1958  November          52.48
    ## 682 1958   October          51.33
    ## 683 1958 September          50.06
    ## 684 1958    August          47.75
    ## 685 1958      July          47.19
    ## 686 1958      June          45.24
    ## 687 1958       May          44.09
    ## 688 1958     April          43.44
    ## 689 1958     March          42.10
    ## 690 1958  February          40.84
    ## 691 1958   January          41.70
    ## 692 1957  December          39.99
    ## 693 1957  November          41.72
    ## 694 1957   October          41.06
    ## 695 1957 September          42.42
    ## 696 1957    August          45.22
    ## 697 1957      July          47.91
    ## 698 1957      June          47.37
    ## 699 1957       May          47.43
    ## 700 1957     April          45.74
    ## 701 1957     March          44.11
    ## 702 1957  February          43.26
    ## 703 1957   January          44.72
    ## 704 1956  December          46.67
    ## 705 1956  November          45.08
    ## 706 1956   October          45.58
    ## 707 1956 September          45.35
    ## 708 1956    August          47.51
    ## 709 1956      July          49.39
    ## 710 1956      June          46.97
    ## 711 1956       May          45.20
    ## 712 1956     April          48.38
    ## 713 1956     March          48.48
    ## 714 1956  February          45.34
    ## 715 1956   January          43.82
    ## 716 1955  December          45.48
    ## 717 1955  November          45.51
    ## 718 1955   October          42.34
    ## 719 1955 September          43.67
    ## 720 1955    August          43.18
    ## 721 1955      July          43.52
    ## 722 1955      June          41.03
    ## 723 1955       May          37.91
    ## 724 1955     April          37.96
    ## 725 1955     March          36.58
    ## 726 1955  February          36.76
    ## 727 1955   January          36.63
    ## 728 1954  December          35.98
    ## 729 1954  November          34.24
    ## 730 1954   October          31.68
    ## 731 1954 September          32.31
    ## 732 1954    August          29.83
    ## 733 1954      July          30.88
    ## 734 1954      June          29.21
    ## 735 1954       May          29.19
    ## 736 1954     April          28.26
    ## 737 1954     March          26.94
    ## 738 1954  February          26.15
    ## 739 1954   January          26.08
    ## 740 1953  December          24.81
    ## 741 1953  November          24.76
    ## 742 1953   October          24.54
    ## 743 1953 September          23.35
    ## 744 1953    August          23.32
    ## 745 1953      July          24.75
    ## 746 1953      June          24.14
    ## 747 1953       May          24.54
    ## 748 1953     April          24.62
    ## 749 1953     March          25.29
    ## 750 1953  February          25.90
    ## 751 1953   January          26.38
    ## 752 1952  December          26.57
    ## 753 1952  November          25.66
    ## 754 1952   October          24.52
    ## 755 1952 September          24.54
    ## 756 1952    August          25.03
    ## 757 1952      July          25.40
    ## 758 1952      June          24.96
    ## 759 1952       May          23.86
    ## 760 1952     April          23.32
    ## 761 1952     March          24.37
    ## 762 1952  February          23.26
    ## 763 1952   January          24.14
    ## 764 1951  December          23.77
    ## 765 1951  November          22.88
    ## 766 1951   October          22.94
    ## 767 1951 September          23.26
    ## 768 1951    August          23.28
    ## 769 1951      July          22.40
    ## 770 1951      June          20.96
    ## 771 1951       May          21.52
    ## 772 1951     April          22.43
    ## 773 1951     March          21.48
    ## 774 1951  February          21.80
    ## 775 1951   January          21.66
    ## 776 1950  December          20.43
    ## 777 1950  November          19.51
    ## 778 1950   October          19.53
    ## 779 1950 September          19.45
    ## 780 1950    August          18.42
    ## 781 1950      July          17.84
    ## 782 1950      June          17.69
    ## 783 1950       May          18.78
    ## 784 1950     April          17.96
    ## 785 1950     March          17.29
    ## 786 1950  February          17.22
    ## 787 1950   January          17.05

``` r
# import and clean unemployment data

unemploy_df =
  read.csv("./data/fivethirtyeight_datasets/unemployment.csv") %>%
  janitor::clean_names(dat = .) 

unemploy_df
```

    ##    year  jan  feb  mar  apr  may  jun jul aug  sep  oct  nov  dec
    ## 1  1948  3.4  3.8  4.0  3.9  3.5  3.6 3.6 3.9  3.8  3.7  3.8  4.0
    ## 2  1949  4.3  4.7  5.0  5.3  6.1  6.2 6.7 6.8  6.6  7.9  6.4  6.6
    ## 3  1950  6.5  6.4  6.3  5.8  5.5  5.4 5.0 4.5  4.4  4.2  4.2  4.3
    ## 4  1951  3.7  3.4  3.4  3.1  3.0  3.2 3.1 3.1  3.3  3.5  3.5  3.1
    ## 5  1952  3.2  3.1  2.9  2.9  3.0  3.0 3.2 3.4  3.1  3.0  2.8  2.7
    ## 6  1953  2.9  2.6  2.6  2.7  2.5  2.5 2.6 2.7  2.9  3.1  3.5  4.5
    ## 7  1954  4.9  5.2  5.7  5.9  5.9  5.6 5.8 6.0  6.1  5.7  5.3  5.0
    ## 8  1955  4.9  4.7  4.6  4.7  4.3  4.2 4.0 4.2  4.1  4.3  4.2  4.2
    ## 9  1956  4.0  3.9  4.2  4.0  4.3  4.3 4.4 4.1  3.9  3.9  4.3  4.2
    ## 10 1957  4.2  3.9  3.7  3.9  4.1  4.3 4.2 4.1  4.4  4.5  5.1  5.2
    ## 11 1958  5.8  6.4  6.7  7.4  7.4  7.3 7.5 7.4  7.1  6.7  6.2  6.2
    ## 12 1959  6.0  5.9  5.6  5.2  5.1  5.0 5.1 5.2  5.5  5.7  5.8  5.3
    ## 13 1960  5.2  4.8  5.4  5.2  5.1  5.4 5.5 5.6  5.5  6.1  6.1  6.6
    ## 14 1961  6.6  6.9  6.9  7.0  7.1  6.9 7.0 6.6  6.7  6.5  6.1  6.0
    ## 15 1962  5.8  5.5  5.6  5.6  5.5  5.5 5.4 5.7  5.6  5.4  5.7  5.5
    ## 16 1963  5.7  5.9  5.7  5.7  5.9  5.6 5.6 5.4  5.5  5.5  5.7  5.5
    ## 17 1964  5.6  5.4  5.4  5.3  5.1  5.2 4.9 5.0  5.1  5.1  4.8  5.0
    ## 18 1965  4.9  5.1  4.7  4.8  4.6  4.6 4.4 4.4  4.3  4.2  4.1  4.0
    ## 19 1966  4.0  3.8  3.8  3.8  3.9  3.8 3.8 3.8  3.7  3.7  3.6  3.8
    ## 20 1967  3.9  3.8  3.8  3.8  3.8  3.9 3.8 3.8  3.8  4.0  3.9  3.8
    ## 21 1968  3.7  3.8  3.7  3.5  3.5  3.7 3.7 3.5  3.4  3.4  3.4  3.4
    ## 22 1969  3.4  3.4  3.4  3.4  3.4  3.5 3.5 3.5  3.7  3.7  3.5  3.5
    ## 23 1970  3.9  4.2  4.4  4.6  4.8  4.9 5.0 5.1  5.4  5.5  5.9  6.1
    ## 24 1971  5.9  5.9  6.0  5.9  5.9  5.9 6.0 6.1  6.0  5.8  6.0  6.0
    ## 25 1972  5.8  5.7  5.8  5.7  5.7  5.7 5.6 5.6  5.5  5.6  5.3  5.2
    ## 26 1973  4.9  5.0  4.9  5.0  4.9  4.9 4.8 4.8  4.8  4.6  4.8  4.9
    ## 27 1974  5.1  5.2  5.1  5.1  5.1  5.4 5.5 5.5  5.9  6.0  6.6  7.2
    ## 28 1975  8.1  8.1  8.6  8.8  9.0  8.8 8.6 8.4  8.4  8.4  8.3  8.2
    ## 29 1976  7.9  7.7  7.6  7.7  7.4  7.6 7.8 7.8  7.6  7.7  7.8  7.8
    ## 30 1977  7.5  7.6  7.4  7.2  7.0  7.2 6.9 7.0  6.8  6.8  6.8  6.4
    ## 31 1978  6.4  6.3  6.3  6.1  6.0  5.9 6.2 5.9  6.0  5.8  5.9  6.0
    ## 32 1979  5.9  5.9  5.8  5.8  5.6  5.7 5.7 6.0  5.9  6.0  5.9  6.0
    ## 33 1980  6.3  6.3  6.3  6.9  7.5  7.6 7.8 7.7  7.5  7.5  7.5  7.2
    ## 34 1981  7.5  7.4  7.4  7.2  7.5  7.5 7.2 7.4  7.6  7.9  8.3  8.5
    ## 35 1982  8.6  8.9  9.0  9.3  9.4  9.6 9.8 9.8 10.1 10.4 10.8 10.8
    ## 36 1983 10.4 10.4 10.3 10.2 10.1 10.1 9.4 9.5  9.2  8.8  8.5  8.3
    ## 37 1984  8.0  7.8  7.8  7.7  7.4  7.2 7.5 7.5  7.3  7.4  7.2  7.3
    ## 38 1985  7.3  7.2  7.2  7.3  7.2  7.4 7.4 7.1  7.1  7.1  7.0  7.0
    ## 39 1986  6.7  7.2  7.2  7.1  7.2  7.2 7.0 6.9  7.0  7.0  6.9  6.6
    ## 40 1987  6.6  6.6  6.6  6.3  6.3  6.2 6.1 6.0  5.9  6.0  5.8  5.7
    ## 41 1988  5.7  5.7  5.7  5.4  5.6  5.4 5.4 5.6  5.4  5.4  5.3  5.3
    ## 42 1989  5.4  5.2  5.0  5.2  5.2  5.3 5.2 5.2  5.3  5.3  5.4  5.4
    ## 43 1990  5.4  5.3  5.2  5.4  5.4  5.2 5.5 5.7  5.9  5.9  6.2  6.3
    ## 44 1991  6.4  6.6  6.8  6.7  6.9  6.9 6.8 6.9  6.9  7.0  7.0  7.3
    ## 45 1992  7.3  7.4  7.4  7.4  7.6  7.8 7.7 7.6  7.6  7.3  7.4  7.4
    ## 46 1993  7.3  7.1  7.0  7.1  7.1  7.0 6.9 6.8  6.7  6.8  6.6  6.5
    ## 47 1994  6.6  6.6  6.5  6.4  6.1  6.1 6.1 6.0  5.9  5.8  5.6  5.5
    ## 48 1995  5.6  5.4  5.4  5.8  5.6  5.6 5.7 5.7  5.6  5.5  5.6  5.6
    ## 49 1996  5.6  5.5  5.5  5.6  5.6  5.3 5.5 5.1  5.2  5.2  5.4  5.4
    ## 50 1997  5.3  5.2  5.2  5.1  4.9  5.0 4.9 4.8  4.9  4.7  4.6  4.7
    ## 51 1998  4.6  4.6  4.7  4.3  4.4  4.5 4.5 4.5  4.6  4.5  4.4  4.4
    ## 52 1999  4.3  4.4  4.2  4.3  4.2  4.3 4.3 4.2  4.2  4.1  4.1  4.0
    ## 53 2000  4.0  4.1  4.0  3.8  4.0  4.0 4.0 4.1  3.9  3.9  3.9  3.9
    ## 54 2001  4.2  4.2  4.3  4.4  4.3  4.5 4.6 4.9  5.0  5.3  5.5  5.7
    ## 55 2002  5.7  5.7  5.7  5.9  5.8  5.8 5.8 5.7  5.7  5.7  5.9  6.0
    ## 56 2003  5.8  5.9  5.9  6.0  6.1  6.3 6.2 6.1  6.1  6.0  5.8  5.7
    ## 57 2004  5.7  5.6  5.8  5.6  5.6  5.6 5.5 5.4  5.4  5.5  5.4  5.4
    ## 58 2005  5.3  5.4  5.2  5.2  5.1  5.0 5.0 4.9  5.0  5.0  5.0  4.9
    ## 59 2006  4.7  4.8  4.7  4.7  4.6  4.6 4.7 4.7  4.5  4.4  4.5  4.4
    ## 60 2007  4.6  4.5  4.4  4.5  4.4  4.6 4.7 4.6  4.7  4.7  4.7  5.0
    ## 61 2008  5.0  4.9  5.1  5.0  5.4  5.6 5.8 6.1  6.1  6.5  6.8  7.3
    ## 62 2009  7.8  8.3  8.7  9.0  9.4  9.5 9.5 9.6  9.8 10.0  9.9  9.9
    ## 63 2010  9.8  9.8  9.9  9.9  9.6  9.4 9.4 9.5  9.5  9.4  9.8  9.3
    ## 64 2011  9.2  9.0  9.0  9.1  9.0  9.1 9.0 9.0  9.0  8.8  8.6  8.5
    ## 65 2012  8.3  8.3  8.2  8.2  8.2  8.2 8.2 8.0  7.8  7.8  7.7  7.9
    ## 66 2013  8.0  7.7  7.5  7.6  7.5  7.5 7.3 7.2  7.2  7.2  7.0  6.7
    ## 67 2014  6.6  6.7  6.6  6.2  6.3  6.1 6.2 6.1  5.9  5.7  5.8  5.6
    ## 68 2015  5.7  5.5  5.5  5.4  5.5  5.3  NA  NA   NA   NA   NA   NA

``` r
# convert the months from rows to columns in the unemployment data frame

unemploy_data_col = 
  pivot_longer(
    unemploy_df,
    jan:dec,
    names_to = "month",
    values_to = "percent_unemploy")

unemploy_data_col
```

    ## # A tibble: 816 x 3
    ##     year month percent_unemploy
    ##    <int> <chr>            <dbl>
    ##  1  1948 jan                3.4
    ##  2  1948 feb                3.8
    ##  3  1948 mar                4  
    ##  4  1948 apr                3.9
    ##  5  1948 may                3.5
    ##  6  1948 jun                3.6
    ##  7  1948 jul                3.6
    ##  8  1948 aug                3.9
    ##  9  1948 sep                3.8
    ## 10  1948 oct                3.7
    ## # … with 806 more rows

``` r
# convert the abbreviated months to full names 

unemploy_tidy_data = 
  unemploy_data_col %>%
  mutate(.data = ., 
         month = recode(month, 
                        `jan` = "January", 
                        `feb` = "February",
                        `mar` = "March", 
                        `apr` = "April",
                        `may` = "May",
                        `jun` = "June",
                        `jul` = "July",
                        `aug` = "August",
                        `sep` = "September",
                       `oct` = "October",
                        `nov` = "November",
                        `dec` = "December"))

unemploy_tidy_data
```

    ## # A tibble: 816 x 3
    ##     year month     percent_unemploy
    ##    <int> <chr>                <dbl>
    ##  1  1948 January                3.4
    ##  2  1948 February               3.8
    ##  3  1948 March                  4  
    ##  4  1948 April                  3.9
    ##  5  1948 May                    3.5
    ##  6  1948 June                   3.6
    ##  7  1948 July                   3.6
    ##  8  1948 August                 3.9
    ##  9  1948 September              3.8
    ## 10  1948 October                3.7
    ## # … with 806 more rows

The following code chunk combines the three individual datasets, seen
above, together.

``` r
# merge pols_month_df and snp_df 

pol_snp_data =
  left_join(snp_df, pols_month_df, by = c("year", "month")) %>%
  mutate(.data = ., year = as.integer(year))

# merge unemploy_tidy_data into pols_snp_data 

pol_snp_unemploy_data =
  left_join(unemploy_tidy_data, pol_snp_data, by = c("year", "month"))
```

As a result of merging three separate datasets, the resulting dataset is
816 rows by 11 columns. The data are for the years, 1948-2015. This
dataset consists of key variables around whether national politicians
(governors, senators, presidents and representatives) were Democratic or
Republican at a given year (*gov\_gop*, *gov\_dem*, *sen\_gop*,
*sen\_dem*, *rep\_gop*, *rep\_dem*, *president*), the closing values of
the Standard & Poor’s (S\&P) stock market index in a given month and
year (*closing\_values*), and the percentage of unemployment in a given
month and year (*percent\_unemploy*).

## Problem 3

We are using the NYC Popular Baby Names dataset.

``` r
# import Popular_Baby_Names csv and clean data 

baby_names_df = 
  read.csv("./data/Popular_Baby_Names.csv") %>%
  janitor::clean_names(dat = .) %>%
  rename(.data = ., child_first_name = child_s_first_name, num_children = count) %>%
  mutate(.data = ., 
         child_first_name = str_to_upper(child_first_name),
         ethnicity = recode(ethnicity, 
                            `ASIAN AND PACI` = "ASIAN AND PACIFIC ISLANDER",
                            `BLACK NON HISP` = "BLACK NON HISPANIC",
                            `WHITE NON HISP` = "WHITE NON HISPANIC")) %>%
  distinct(.data = ., .keep_all = FALSE)
```

We will create a reader-friendly table showing the rank in popularity of
the name “Olivia” as a female baby name over time.

``` r
baby_names_df %>%
  filter(.data = ., child_first_name == "OLIVIA") %>%
  pivot_wider(names_from = "year_of_birth",
              values_from = "rank") %>%
  select(.data = ., -child_first_name, everything(), -num_children, -gender) %>%
  group_by(.data = ., ethnicity) %>%
  fill("2016", "2015", "2014", "2013", "2012", "2011") %>%
  fill("2016", "2015", "2014", "2013", "2012", "2011", .direction = 'up') %>%
  distinct() %>%
  knitr::kable(caption = "Table 1. Popularity of the name, Olivia, by ethnicity and year")
```

| ethnicity                  | 2016 | 2015 | 2014 | 2013 | 2012 | 2011 | child\_first\_name |
| :------------------------- | ---: | ---: | ---: | ---: | ---: | ---: | :----------------- |
| ASIAN AND PACIFIC ISLANDER |    1 |    1 |    1 |    3 |    3 |    4 | OLIVIA             |
| BLACK NON HISPANIC         |    8 |    4 |    8 |    6 |    8 |   10 | OLIVIA             |
| HISPANIC                   |   13 |   16 |   16 |   22 |   22 |   18 | OLIVIA             |
| WHITE NON HISPANIC         |    1 |    1 |    1 |    1 |    4 |    2 | OLIVIA             |

Table 1. Popularity of the name, Olivia, by ethnicity and year

We will create a reader-friendly table showing the most popular male
name (rank = 1) for all ethnicities and all years.

``` r
baby_names_df %>%
  filter(.data = ., gender == "MALE", rank == "1") %>%
  pivot_wider(names_from = "year_of_birth",
              values_from = "child_first_name") %>%
  select(.data = ., -rank, -num_children, -gender) %>%
  group_by(.data = ., ethnicity) %>%
  fill("2016", "2015", "2014", "2013", "2012", "2011") %>%
  fill("2016", "2015", "2014", "2013", "2012", "2011", .direction = 'up') %>%
  distinct() %>%
  knitr::kable(caption = "Table 2. Most popular male first name by ethnicity and year")
```

| ethnicity                  | 2016   | 2015   | 2014   | 2013   | 2012   | 2011    |
| :------------------------- | :----- | :----- | :----- | :----- | :----- | :------ |
| ASIAN AND PACIFIC ISLANDER | ETHAN  | JAYDEN | JAYDEN | JAYDEN | RYAN   | ETHAN   |
| BLACK NON HISPANIC         | NOAH   | NOAH   | ETHAN  | ETHAN  | JAYDEN | JAYDEN  |
| HISPANIC                   | LIAM   | LIAM   | LIAM   | JAYDEN | JAYDEN | JAYDEN  |
| WHITE NON HISPANIC         | JOSEPH | DAVID  | JOSEPH | DAVID  | JOSEPH | MICHAEL |

Table 2. Most popular male first name by ethnicity and year

We will now create a scatterplot to display the data on the popularity
of first names for male, white non-hispanic children born in 2016

``` r
baby_names_df %>%
  filter(.data = ., 
         year_of_birth == "2016" & 
         gender == "MALE" & 
         ethnicity == "WHITE NON HISPANIC") %>%
  ggplot(aes(x = rank, y = num_children)) +
  geom_point(aes(), alpha = .5) + 
  labs(
    title = "Popularity of first name among male, white non-hispanic children born in 2016",
    x = "Rank in popularity of name",
    y = "Number of children with name"
  ) +
  theme_minimal()
```

<img src="p8105_hw2_lk2761_files/figure-gfm/create scatterplot-1.png" width="90%" />
