---
title: "p8105_hw2_lk2761"
author: "Lorraine Kwok"
date: "09/27/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

## Problem 1

This problem uses the Mr. Trash Wheel dataset. 

```{r clean Mr. Trash Wheel sheet}
# import and clean Mr. Trash Wheel sheet 
trash_wheel_data = 
  read_excel("data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
             sheet = 1, 
             range = cell_cols("A:N")) %>%
  janitor::clean_names(dat = .) %>%
  drop_na(data = ., dumpster) %>%
  mutate(.data = ., 
         round(sports_balls, digits = 0),
         as.integer(sports_balls))
```

```{r df for precipitation 2017 and 2018}
precip_2017 = 
  read_excel("data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
             sheet = 4) %>%
  janitor::clean_names(dat = .) %>%
  rename(.data = ., month = precipitation_in, total_inches = x2) %>%
  filter(.data = ., month != "Month") %>%
  drop_na(data = .)  %>%
  mutate(.data = ., year = 2017) 
  
precip_2018 = 
   read_excel("data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
             sheet = 3) %>%
  janitor::clean_names(dat = .) %>%
  rename(.data = ., month = precipitation_in, total_inches = x2) %>%
  filter(.data = ., month != "Month") %>%
  drop_na(data = .) %>%
  mutate(.data = ., year = 2018) 

# create new dataset by combining precip_2017 and precip_2018
precip_combined = bind_rows(precip_2017, precip_2018)
```


